package main

// Graded exercises for the original systems and AI concepts, keyed by
// Concept.Name and merged in by init() in explainers.go. Newer stages set
// their exercises inline. Every concept gets the same ladder: a warm-up
// you can do with pen and paper, a practice task, and a real-world project.

var conceptExercises = map[string][]Exercise{
	// ---------------- Stage 5: The Iron Layer ----------------
	"The Compilation Pipeline": trio(
		"Put these in order and say what each hands to the next: linker, parser, lexer, assembler, optimizer, code generator.",
		"Characters → tokens → tree → IR → assembly → object files → executable.",
		"Compile a small C file one step at a time with gcc -E, -S, -c and a final link, and open each intermediate file to see what changed.",
		"gcc -E main.c | less shows the preprocessed source.",
		`A colleague's build fails with "undefined reference to compute_tax". Reproduce this error with two C files, explain which stage failed and why, and fix it.`,
		"The function is declared, but its object file is not being linked.",
	),
	"Registers, the Stack & Calling Conventions": trio(
		"Draw the stack after main() calls f(2), which calls g(5). What is on top, and what happens when g returns?",
		"Each call pushes a frame; each return pops one.",
		"Write a recursive function with no base case, find the depth at which it crashes, then change the stack size (ulimit -s on Linux) and observe the difference.",
		"Print the depth every 1,000 calls.",
		"Recursive folder walkers can crash on very deep directory trees. Write one that lists every file under a folder, then rewrite it with an explicit stack so it can never overflow the call stack.",
		"A list used as a stack of folders still to visit.",
	),
	"Integers & Floating Point in Bits": trio(
		"What is 255 + 1 in an 8-bit unsigned integer? What is 127 + 1 in an 8-bit signed integer?",
		"Both wrap around: to 0 and to −128.",
		"Write a function that adds money amounts exactly using integer cents, and show a case where floats go visibly wrong, such as adding 0.10 a thousand times.",
		"sum([0.1] * 1000) is not exactly 100.",
		"A game stores the player's score in a 32-bit signed integer, and players earn 1,000 points per second. When does it overflow, and how would you fix it?",
		"2,147,483,647 / 1,000 seconds ≈ 24.9 days. Use a 64-bit integer.",
	),
	"The Memory Hierarchy & Locality": trio(
		"Rank from fastest to slowest, and from smallest to largest: L1 cache, SSD, RAM, registers, L3 cache, a network drive.",
		"Faster is always smaller.",
		"Benchmark summing a large 2D array row by row versus column by column in C, Go or Rust, and report the ratio for several array sizes.",
		"Make the array larger than your L3 cache to see the biggest effect.",
		`A particle simulation stores each particle as an object with position, velocity, colour and name. Rewrite it as separate arrays of x, y, vx and vy (a "struct of arrays") and measure the speed-up when updating positions.`,
		"The update loop then touches only the data it needs, contiguously.",
	),
	"Parsing: Recursive Descent & Pratt": trio(
		"Draw the tree for 2 + 3 * 4 - 1, respecting precedence, then evaluate it from the bottom up.",
		"* binds tighter, so 3 * 4 is its own subtree.",
		`Write a tokenizer that splits "price = 3.5 * (qty + 2)" into typed tokens (IDENT, NUMBER, OP, LPAREN and so on).`,
		"Scan one character at a time, grouping digits together and letters together.",
		`Build the formula engine for a spreadsheet: parse formulas such as "=A1 * 2 + SUM(B1, B2)" against a dictionary of cell values, and report clear errors for malformed formulas.`,
		"Extend the Pratt parser with identifiers and function calls.",
	),

	// ---------------- Stage 6: Operating Systems ----------------
	"Processes & the Address Space": trio(
		"Open your system monitor, find the process using the most memory, and note its PID and its number of threads.",
		"Task Manager, Activity Monitor or htop.",
		"Write a program that starts 3 child processes (os.fork() or subprocess) that each print their PID and sleep, while the parent waits for all of them.",
		"os.fork() and os.wait() on Linux and macOS.",
		"A laptop feels slow. Using top/ps or Task Manager, find the top three CPU and memory users, identify what each process is, and write a short report on what you would close or change.",
		"Sort by CPU first, then by memory.",
	),
	"Virtual Memory & Paging": trio(
		"With 4 KiB pages, how many pages does a 1 MiB array occupy? And a 1 GiB array?",
		"1 MiB / 4 KiB = 256 pages; 1 GiB needs 262,144.",
		"Write a program that allocates 2 GB but touches only the first 10 MB, and compare its virtual size with its resident size.",
		"VmSize versus VmRSS in /proc/self/status (Linux), or VSZ versus RSS in ps.",
		"Use mmap to count the lines of a large file (hundreds of MB) without reading it all into memory, and compare speed and memory use with a normal read loop.",
		"Python's mmap module works on Linux, macOS and Windows.",
	),
	"System Calls & Privilege": trio(
		"List five things your text editor does that require a system call.",
		"Opening, reading and writing files; getting the time; talking to the window system…",
		"Copy a 1 GB file using a 1-byte buffer and using a 64 KB buffer, count the syscalls with strace -c (or just time them), and explain the difference.",
		"Every read and every write is one syscall.",
		`Use strace (Linux) or Process Monitor (Windows) to find which configuration files git or python opens at start-up, the technique admins use to debug "why is my setting ignored?".`,
		"strace -e trace=openat git status",
	),
	"Scheduling & Context Switches": trio(
		"With a 10 ms time slice and 3 CPU-busy programs sharing one core, how long does each wait between its turns?",
		"Two other slices: 20 ms.",
		"Start 1, 2, 4, 8 and 16 CPU-busy processes and measure the total throughput. Where does adding more stop helping on your machine?",
		"Compare the answer with your core count.",
		"Music stutters while a big compile runs. Lower the compile's priority (nice on Linux/macOS, priority in Windows Task Manager), observe whether it helps, and explain what the scheduler does with priorities.",
		"nice -n 19 make",
	),
	"Synchronisation & Memory Ordering": trio(
		"Two threads each add 1 to a shared counter 1,000,000 times without a lock. Is the result always 2,000,000? Why might it be less?",
		"count += 1 is really read, add, write.",
		"Reproduce a lost-update race with threads in Go, Java or C, then fix it three ways (a mutex, an atomic counter, per-thread counters summed at the end) and compare their speeds.",
		"go run -race detects the bug for you.",
		"Simulate a ticket shop where 50 concurrent buyers compete for the last 10 seats. Show that it oversells without locking, then fix it.",
		"The check-then-buy must happen inside one critical section.",
	),

	// ---------------- Stage 7: Storage Engines ----------------
	"Durability: Page Cache, fsync & Atomic Rename": trio(
		"Put the steps of a safe save in order: rename, write temp file, fsync directory, fsync file.",
		"Write the temp file, fsync it, rename it, then fsync the directory.",
		"Write a safe saver (temp file + fsync + rename) and a naive one. Kill each with kill -9 in the middle of large writes many times, and check which ever leaves a corrupted file.",
		"Include a checksum in the file so corruption is detectable.",
		"Your note-taking app loses the last minute of notes after crashes. Add an autosave that writes safely every 30 seconds, and a start-up step that recovers the newest valid save.",
		"Keep the previous good file until the new one is fully written.",
	),
	"B-Trees": trio(
		"A B-tree node holds 200 keys. How many levels are needed for 8 million keys?",
		"200³ = 8,000,000, so three levels.",
		"Create a SQLite table with 1 million rows, time a lookup on an unindexed column, then CREATE INDEX and time it again. Use EXPLAIN QUERY PLAN to see the difference.",
		"The plan changes from SCAN to SEARCH … USING INDEX.",
		`An online shop's "orders for this customer" page is slow. Given its query and table, choose the right index (single-column or composite), add it, and measure the improvement.`,
		"Index the WHERE columns first, then the ORDER BY columns.",
	),
	"LSM-Trees": trio(
		"Writes to key x arrive in order: x=1, x=2, delete x, x=3. What does a read of x return at the end, and what is a tombstone?",
		"The newest entry wins: 3. A delete is written as a tombstone record.",
		"Build a mini-LSM: an in-memory dictionary that flushes to a sorted file every 1,000 keys, reads that check memory and then files from newest to oldest, and a compaction step that merges the files.",
		"Keeping the files sorted lets you binary-search and merge them.",
		"Your app ingests 50,000 sensor readings per second and a B-tree database cannot keep up. Explain why an LSM store copes better, and benchmark inserts in SQLite against your mini-LSM or a RocksDB-based store.",
		"Batch the writes, and compare throughput.",
	),
	"Write-Ahead Logging & Recovery": trio(
		"Why must the log record reach the disk before the data page it describes?",
		"Otherwise a crash could leave a change on disk with no record to redo or undo it.",
		"Add a write-ahead log to a key-value dictionary: append each operation to a log file and fsync it, and on start-up rebuild the dictionary by replaying the log.",
		`One line per operation: "SET key value" or "DEL key".`,
		"Turn on SQLite's WAL mode (PRAGMA journal_mode=WAL) and measure small transactions per second with and without it, and with synchronous=NORMAL versus FULL. Explain the durability trade-off.",
		"Time 10,000 single-row inserts, each in its own transaction.",
	),
	"Transactions, Isolation & MVCC": trio(
		"A transfer moves £50 from A to B in two steps. What can go wrong if the system crashes between the steps, without a transaction?",
		"The money disappears from A without arriving at B.",
		"In SQLite or PostgreSQL, write a transfer that uses a transaction, simulate a failure halfway through (raise an exception), and verify that both balances are unchanged.",
		"BEGIN … COMMIT, or ROLLBACK on error.",
		"Two people book the last hotel room at the same instant. Reproduce the double booking with two concurrent database sessions, then prevent it with SELECT … FOR UPDATE, a unique constraint, or SERIALIZABLE isolation.",
		"Two psql windows make this easy to demonstrate in PostgreSQL.",
	),

	// ---------------- Stage 8: Networks ----------------
	"The Layered Stack & Encapsulation": trio(
		"For sending a chat message over Wi-Fi, name what happens at the application, transport, network and link layers.",
		"Message → TCP/QUIC segment → IP packet → Wi-Fi frame.",
		"Capture your own traffic with Wireshark while loading a website, and find one packet showing each layer: Wi-Fi/Ethernet, IP, TCP and TLS.",
		`Filter with "tcp.port == 443".`,
		"Your home internet is slow. Use ping, traceroute (tracert on Windows) and a speed test to work out whether the problem is your Wi-Fi, your router or your provider, and write down your reasoning.",
		"Ping your router first, then a public server.",
	),
	"TCP: Handshake, Flow & Congestion Control": trio(
		"Why do video calls usually run over UDP-based protocols rather than TCP?",
		"A late video frame is useless, and waiting for its retransmission adds delay.",
		"Write a client and server that send a file over TCP and verify it with a checksum at the other end. Then add artificial delay and loss (tc netem on Linux) and measure the effect.",
		"Send the file size first, so the receiver knows when it is done.",
		"Implement reliable delivery over UDP (sequence numbers, acknowledgements and retransmission on timeout) and test it by randomly dropping 10% of packets on purpose.",
		"Start with stop-and-wait, then allow several packets in flight (a window).",
	),
	"Sockets & I/O Multiplexing": trio(
		"What do bind, listen, accept and connect each do? Which are used by the server and which by the client?",
		"Only the client calls connect.",
		"Write a chat server where several clients connect with nc or telnet and every message is broadcast to everyone, first with one thread per client, then with select or asyncio.",
		"Keep a list of the connected sockets.",
		"Load-test your chat server with 1,000 simulated clients, measure memory use and latency for the threaded and event-loop versions, and explain the difference.",
		"Write the load generator with asyncio so it can open many connections cheaply.",
	),
	"Time, Clocks & Ordering": trio(
		"A sends m1 to B; after receiving it, B sends m2 to C. Meanwhile C performs an event e without talking to anyone. Which pairs of events are causally ordered?",
		"m1 happens before m2; e is concurrent with both.",
		"Implement Lamport clocks for three simulated processes that exchange random messages, and print a total order of all events that respects causality.",
		"On receive: clock = max(local, received) + 1.",
		"Two phones edit the same shared note offline and sync later. Use vector clocks to detect conflicting edits, implement it for two replicas, and show a detected conflict.",
		"If neither vector is ≥ the other in every entry, the edits were concurrent.",
	),
	"Consensus & Replication (Raft)": trio(
		"A 5-node Raft cluster loses 2 nodes. Can it still commit writes? What if it loses 3?",
		"A majority of 5 is 3: yes with 3 nodes left, no with only 2.",
		"Use the visualisation at raft.github.io to cause a leader failure and a network split, and record the term numbers and which node became leader each time.",
		"Click a node to stop it or restart it.",
		"Run a 3-node etcd cluster locally (for example with Docker Compose), write some keys, kill the leader, and time how long it takes until writes succeed again.",
		"etcdctl endpoint status shows which node is the leader.",
	),

	// ---------------- Stage 13: Mathematical Foundations ----------------
	"Matrices as Linear Maps": trio(
		"What does the matrix [[0, −1], [1, 0]] do to the point (1, 0)? And to (0, 1)?",
		"It rotates them 90° anticlockwise, to (0, 1) and (−1, 0).",
		"Apply rotation, scaling and shear matrices to the corners of a square and draw the results, including a combination made by multiplying two matrices.",
		"Order matters: rotating then scaling is not the same as scaling then rotating.",
		"Write two photo filters: greyscale, and a sepia filter that multiplies every pixel's (R, G, B) vector by a fixed 3×3 matrix.",
		"new = M × (r, g, b), then clip each value to 0–255.",
	),
	"Eigenvectors & the SVD": trio(
		"A 1000×1000 image is approximated at rank 20. How many numbers are stored (U, Σ, V), compared with the original?",
		"20 × (1000 + 1000 + 1) = 40,020, versus 1,000,000.",
		"Use numpy.linalg.svd to compress a greyscale photo at ranks 5, 20 and 100, and plot quality against storage.",
		"Reconstruct with U[:, :k] @ diag(S[:k]) @ Vt[:k].",
		"Build a small film recommender: make a users × films ratings matrix (friends' ratings, or the MovieLens small dataset), fill in missing values, predict unrated films with a low-rank SVD, and check whether the recommendations make sense.",
		"Fill missing values with each user's mean rating before the SVD.",
	),
	"Gradients, Jacobians & the Matrix Chain Rule": trio(
		"For f(x) = (3x + 1)², compute df/dx with the chain rule and evaluate it at x = 1.",
		"2(3x + 1) · 3, which is 24 at x = 1.",
		"Write a finite-difference gradient checker and use it to verify your hand-derived gradients for f(W) = ‖Wx − t‖² with random matrices.",
		"(f(w + h) − f(w − h)) / 2h, with h ≈ 1e-5.",
		"A delivery plan costs 0.5·distance + 2·stops + 0.1·distance·stops. At the current plan (distance 100, stops 10), compute how sensitive the cost is to each input, and say which lever to pull first.",
		"∂cost/∂distance = 0.5 + 0.1·stops = 1.5; ∂cost/∂stops = 2 + 0.1·distance = 12.",
	),
	"Probability, Softmax & Cross-Entropy": trio(
		"Compute softmax([1, 2, 3]) by hand (e ≈ 2.718). What is the cross-entropy loss if the true class is the first one?",
		"About [0.09, 0.24, 0.67]; the loss is −ln(0.09) ≈ 2.4.",
		"Implement numerically stable softmax and log-softmax and test them on very large and very negative inputs, comparing with a naive version.",
		"Subtract the maximum first; log-softmax = z − max − log Σ exp(z − max).",
		"Write a next-word predictor: count which words follow each word in a book, turn the counts into probabilities, generate text by sampling, and measure the average cross-entropy on a held-out chapter.",
		"Add-one smoothing avoids zero probabilities for unseen word pairs.",
	),
	"Optimisation: From Gradient Descent to Adam": trio(
		"Minimise f(x) = (x − 3)², starting at x = 0 with a learning rate of 0.1. Write down the first three steps.",
		"The gradient is 2(x − 3), so x becomes 0.6, then 1.08, then 1.464.",
		"Implement gradient descent, momentum and Adam from scratch, race them on the Rosenbrock function, and plot their paths and their loss per step.",
		"Rosenbrock is (1 − x)² + 100(y − x²)², with its minimum at (1, 1).",
		"A product's demand is 1000 − 20·price and each unit costs 10 to make. Find the profit-maximising price with gradient ascent, then check it with calculus.",
		"Profit = (price − 10)(1000 − 20·price), which peaks at a price of 30.",
	),

	// ---------------- Stage 15: Neural Networks & Autograd ----------------
	"Computational Graphs & Reverse-Mode Autodiff": trio(
		"For L = (w·x + b − t)² with w = 2, x = 3, b = 1 and t = 5, compute L, dL/dw and dL/db by hand.",
		"y = 7 and L = 4; dL/dy = 4, so dL/dw = 12 and dL/db = 4.",
		"Build a scalar autograd Value class supporting +, ×, tanh and backward(), and check its gradients against your Stage 13 finite-difference checker.",
		"Each operation stores a small closure that pushes gradients to its inputs.",
		"Use your autograd engine to fit a line to real data (monthly temperatures, or your running pace over several weeks) by minimising squared error, and compare the result with the exact least-squares solution.",
		"There are just two parameters, w and b, updated by gradient descent.",
	),
	"MLPs, Activations & Initialisation": trio(
		"Why can no single straight line separate XOR, with (0,0) and (1,1) in one class and (0,1) and (1,0) in the other? What does a hidden layer add?",
		"The classes sit on opposite corners; a hidden layer can bend the boundary.",
		"Train a 2-layer MLP to learn XOR (from scratch or with your autograd engine), then remove the activation function and watch it fail.",
		"Use tanh or ReLU with 4 to 8 hidden units.",
		"Train a small MLP on the MNIST handwritten digits to at least 95% test accuracy, then compare a poor initialisation with Kaiming initialisation.",
		"Scale pixels to the range 0–1 and flatten each image to 784 numbers.",
	),
	"Residual Connections & Normalisation": trio(
		"If each layer multiplies the signal by 0.9, how strong is it after 50 layers? With a residual connection, what does each layer need to learn?",
		"0.9⁵⁰ ≈ 0.005. The residual path carries the signal through unchanged, so each layer only learns a correction.",
		"Implement LayerNorm from scratch, check that each example's output has mean ≈ 0 and variance ≈ 1, and compare it with PyTorch's nn.LayerNorm.",
		"Normalise across the features, then apply a learnable scale and shift.",
		"Train a 20-layer MLP on MNIST with and without residual connections, plot both training-loss curves, and write a short explanation for a colleague of why one trains and the other does not.",
		"Keep everything else identical and only add x + f(x).",
	),
	"Attention & the Transformer": trio(
		"One query gives attention scores [2, 1, 0] for three tokens. After softmax, roughly what weight does each value get?",
		"About [0.67, 0.24, 0.09].",
		"Implement single-head scaled dot-product attention with a causal mask in NumPy, and check that no token's output depends on future tokens.",
		"Set the masked scores to −∞ before the softmax.",
		"Visualise attention in a real model: run a small pretrained transformer (such as GPT-2 via Hugging Face) on a sentence containing a pronoun, plot some heads' attention weights, and find a head that links the pronoun to its noun.",
		"Pass output_attentions=True to get the weights.",
	),
	"The Training Loop & Generalisation": trio(
		"Your training loss keeps falling, but the validation loss started rising after epoch 5. What is happening, and name three things you could try.",
		"Overfitting: get more data, add regularisation, or stop early.",
		"Write a full MNIST training loop with a train/validation split, early stopping, and learning-rate warm-up followed by cosine decay, and plot both loss curves.",
		"Save the model with the best validation loss.",
		"Build an image classifier for your own photos (two kinds of plant, or your pets) by fine-tuning a small pretrained model. Collect and split the data honestly, and report accuracy on photos taken on a different day.",
		"Photos from a different day test whether the model learned the object or just the background.",
	),

	// ---------------- Stage 16: AI Infrastructure ----------------
	"The GPU Execution Model": trio(
		"In a warp of 32 threads, 16 take the if branch and 16 take the else branch. Roughly how much slower is that code than without divergence?",
		"Both paths run one after the other: about 2× slower.",
		"Write a vector-add kernel (CUDA, or Numba/CuPy, for example on a free Google Colab GPU) and compare it with NumPy on the CPU for arrays from a thousand to 100 million elements.",
		"Small arrays are slower on the GPU because of launch and copy overhead.",
		"Speed up a real image job (for example blurring 1,000 photos) on a GPU, measure the end-to-end time including data transfers, and decide whether the GPU was worth it.",
		"For small jobs, copying data to and from the GPU can dominate.",
	),
	"GPU Memory Hierarchy & Coalescing": trio(
		"A warp reads floats at index t (its thread number) versus index 32·t. Roughly how many 128-byte transactions does each pattern need?",
		"Contiguous: 32 × 4 bytes = 128 bytes, one transaction. Strided: about 32.",
		"Write a naive matrix transpose and a shared-memory tiled one, and measure the achieved GB/s of each against your GPU's peak bandwidth.",
		"Use 32×32 tiles, padded to 33 columns to avoid bank conflicts.",
		"Profile a PyTorch training step with torch.profiler, find the three most expensive operations, and decide whether each is compute-bound or memory-bound.",
		"Elementwise operations and normalisation layers are usually memory-bound.",
	),
	"The Roofline Model: Compute- vs Memory-Bound": trio(
		"A kernel does 2 FLOPs for every 8 bytes it loads. On a GPU with 1 TB/s of bandwidth and a 100 TFLOP/s peak, what performance can it reach at most?",
		"0.25 FLOP/byte × 1 TB/s = 0.25 TFLOP/s, so it is memory-bound.",
		"Measure your machine's memory bandwidth (a large array copy) and peak compute (a large matrix multiply), draw its roofline, and plot where a vector add and a big matmul sit on it.",
		"NumPy on the CPU, or PyTorch on a GPU.",
		"You want a local chatbot running an 8-billion-parameter model in 4-bit quantisation. Estimate its tokens per second on three devices from their memory bandwidth, then check one estimate with llama.cpp or Ollama.",
		"8B parameters × 0.5 bytes ≈ 4 GB read per generated token.",
	),
	"Kernel Fusion & FlashAttention": trio(
		"y = relu(x * 2 + 1) runs as three separate kernels on a 1 GB tensor. How much data moves to and from memory, compared with one fused kernel?",
		"Each kernel reads 1 GB and writes 1 GB: 6 GB versus 2 GB.",
		"Implement softmax as a two-pass algorithm and as a single-pass online algorithm, and verify that they agree to within 1e-6 on random inputs.",
		"Keep a running maximum, and rescale the running sum whenever the maximum changes.",
		"Speed up a small PyTorch model with torch.compile (which fuses operations), measure the time per step before and after, and find which operations were fused.",
		"Warm up for a few steps before timing, because compilation happens on the first run.",
	),
	"KV Cache, Batching & PagedAttention": trio(
		"A model has 32 layers, 8 KV heads, head dimension 128 and fp16 values. How many bytes of KV cache does each token need? And an 8,000-token conversation?",
		"2 × 32 × 8 × 128 × 2 bytes = 128 KiB per token, so about 1 GiB for 8,000 tokens.",
		"Write a generation loop for a small model (such as GPT-2) with and without a KV cache, and measure tokens per second as the sequence grows.",
		"Hugging Face models return past_key_values; pass them back in on the next step.",
		"Run a local model server (vLLM, or llama.cpp's server) and measure throughput with 1, 4 and 16 concurrent users. Explain the results using batching and KV-cache memory.",
		"Send the requests from a small asyncio script and record tokens per second.",
	),
}
