package main

// Dictionary: algorithms, security, AI & ML, and programmer culture.

var vocabAlgorithms = []Word{
	{"Algorithm", nil, "Algorithms", 2,
		"A precise, step-by-step method for solving a problem, that always finishes.",
		"A recipe, or the steps for solving a Rubik's cube.",
		`Binary search: look at the middle; throw away the half that cannot contain the answer; repeat.`,
		"An algorithm is the method; a program is one implementation of it in one language.",
		[]string{"Big-O notation", "Data structure", "Program"}},
	{"Data structure", nil, "Algorithms", 2,
		"A way of organising data in memory so certain operations are fast: arrays, linked lists, hash tables, trees, graphs, heaps.",
		"How you organise a kitchen: spices in a rack, pans on hooks, each placed for how you use it.",
		`Need "is x in here?" fast → a set (hash table)
Need items in sorted order → a balanced tree`,
		"Choosing the right data structure usually matters more than clever code.",
		[]string{"Algorithm", "Array", "Dictionary", "Big-O notation"}},
	{"Big-O notation", []string{"big O", "O(n)", "time complexity", "space complexity", "complexity", "asymptotic"}, "Algorithms", 2,
		"A way to describe how an algorithm's time (or memory) grows as the input grows, ignoring constant factors: O(1) constant, O(log n), O(n) linear, O(n log n), O(n²) quadratic.",
		"Looking up a word in a dictionary by halving (log n) versus reading every page (n).",
		`x in my_list      # O(n): checks items one by one
x in my_set       # O(1) on average: jumps straight to it
nested loops over n items: O(n²)`,
		"Big-O describes growth, not speed: an O(n) loop over 10 items can be slower than an O(n²) one. Measure too.",
		[]string{"Algorithm", "Data structure", "Locality"}},
	{"Linked list", nil, "Algorithms", 2,
		"A sequence of nodes where each node holds a value and a pointer to the next node, so items can be anywhere in memory.",
		"A treasure hunt: each clue tells you where the next one is.",
		`struct Node { int value; struct Node *next; };`,
		"Linked lists are fast to insert into but slow to index and unfriendly to caches. Dynamic arrays usually win in practice.",
		[]string{"List", "Pointer", "Array"}},
	{"Tree", []string{"binary tree", "binary search tree", "B-tree", "node", "root", "leaf"}, "Algorithms", 2,
		"A hierarchy of nodes: one root, each node with children, and leaves at the bottom. A binary search tree keeps smaller values left and larger right; a B-tree is the wide, shallow version databases use.",
		"A family tree, or folders inside folders.",
		`        8
      /   \
     3     10
    / \      \
   1   6      14`,
		"Computer science trees are drawn upside down: the root is at the top.",
		[]string{"Graph", "Recursion", "Database index"}},
	{"Graph", []string{"vertex", "edge", "nodes and edges"}, "Algorithms", 2,
		"A set of nodes (vertices) connected by edges. It models networks of all kinds: roads, friendships, links, dependencies.",
		"A map of cities (nodes) joined by roads (edges).",
		`roads = {"A": ["B", "C"], "B": ["D"], "C": ["D"], "D": []}`,
		"Trees are graphs with no cycles and one root. Graph algorithms must handle cycles, or they loop forever.",
		[]string{"Tree", "Algorithm"}},
	{"Hash function", []string{"hash", "hashing", "hash collision"}, "Algorithms", 2,
		"A function that turns any data into a fixed-size number (the hash). The same input always gives the same hash. Hash tables use it to decide where to store things; security uses special cryptographic hashes.",
		"A cloakroom that decides your hook number from the first letter of your name.",
		`hash("hello")                   # some large integer
hashlib.sha256(b"hello").hexdigest()   # cryptographic hash`,
		"A normal hash (for tables) and a cryptographic hash (for security) are different tools. Never use the first for passwords.",
		[]string{"Dictionary", "Password hashing", "Checksum"}},
	{"Sorting", []string{"sort", "sorting algorithm", "stable sort"}, "Algorithms", 2,
		"Putting items in order. Good general-purpose sorts take O(n log n) time. A stable sort keeps equal items in their original order.",
		"Arranging a hand of cards from lowest to highest.",
		`sorted([3, 1, 2])                  # [1, 2, 3]
sorted(people, key=lambda p: p.age)`,
		"Use the language's built-in sort. Writing your own is for learning, not production.",
		[]string{"Big-O notation", "Binary search"}},
	{"Binary search", nil, "Algorithms", 2,
		"Finding an item in a sorted list by checking the middle and discarding the half that cannot contain it, repeatedly. It takes O(log n) steps: about 20 for a million items.",
		"Guessing a number between 1 and 100 when told \"higher\" or \"lower\".",
		`import bisect
i = bisect.bisect_left(sorted_list, target)`,
		"It only works on sorted data, and its boundaries are famously easy to get off by one.",
		[]string{"Sorting", "Big-O notation", "Off-by-one error"}},
	{"Edge case", []string{"corner case", "boundary case"}, "Algorithms", 2,
		"An unusual input at the boundary of what a program handles: an empty list, zero, a negative number, the maximum value, a very long string.",
		"Testing a lift with nobody in it, and with exactly the maximum weight.",
		`average([])          # division by zero?
parse("")            # empty input?
get(items, len(items))   # one past the end?`,
		"Most bugs live at the edges. Test them on purpose.",
		[]string{"Test", "Off-by-one error", "Input validation"}},
	{"Invariant", []string{"loop invariant"}, "Algorithms", 3,
		"A condition that is always true at a certain point in a program, for example at the start of every loop iteration. Reasoning with invariants is how you prove code correct.",
		"The rule that a bank's books always balance, whatever transactions happen.",
		`# invariant: result == sum of items[0:i]
result = 0
for i in range(len(items)):
    result += items[i]`,
		"If you cannot state a loop's invariant, you probably do not fully understand the loop yet.",
		[]string{"Algorithm", "Assertion", "Proof by induction"}},
	{"Proof by induction", []string{"induction", "mathematical induction"}, "Algorithms", 3,
		"A way to prove something for all whole numbers: show it holds for the first case, then show that if it holds for one case, it holds for the next. Recursion is the programming twin of induction.",
		"Dominoes: the first one falls, and each falling domino knocks over the next, so all of them fall.",
		`Claim: 1 + 2 + … + n = n(n+1)/2
Base: n=1 ✓   Step: add n+1 to both sides ✓`,
		"Both parts are needed. A step without a base proves nothing.",
		[]string{"Recursion", "Invariant"}},
	{"Checksum", []string{"CRC", "checksum digest"}, "Algorithms", 8,
		"A small value computed from data so you can detect accidental corruption: if the data changes, the checksum almost certainly changes.",
		"The check digit on a barcode or credit card that catches mistyped numbers.",
		`sha256sum academy     # compare with the published checksum`,
		"Simple checksums catch accidents, not attackers. Use cryptographic signatures against tampering.",
		[]string{"Hash function"}},
}

var vocabSecurity = []Word{
	{"Vulnerability", []string{"vuln", "CVE", "exploit", "zero-day"}, "Security", 10,
		"A weakness an attacker can use to make software do something it should not. An exploit is code that uses it; a CVE is its public ID number; a zero-day is one with no fix yet.",
		"A broken window latch; the exploit is climbing through it.",
		`CVE-2014-0160 ("Heartbleed"): an OpenSSL buffer over-read`,
		"Most real vulnerabilities come from ordinary bugs: unchecked input, memory errors, logic mistakes.",
		[]string{"Buffer overflow", "Injection", "Input validation"}},
	{"Injection", []string{"SQL injection", "command injection", "XSS", "cross-site scripting"}, "Security", 10,
		"An attack where user input is treated as code: SQL (SQL injection), shell commands (command injection) or HTML/JavaScript in a page (XSS).",
		"A form field where someone writes \"…and also give me the keys to the safe\", and the clerk obeys.",
		`# vulnerable
db.execute("SELECT * FROM users WHERE name = '" + name + "'")
# safe: parameters are never treated as SQL
db.execute("SELECT * FROM users WHERE name = ?", (name,))`,
		"Escaping by hand is fragile. Use parameterised queries, safe APIs and auto-escaping templates.",
		[]string{"Input validation", "SQL", "Vulnerability"}},
	{"Input validation", []string{"validation", "sanitization", "sanitize", "sanitise"}, "Security", 10,
		"Checking that input is what you expect (type, length, range, format) before using it, and rejecting it otherwise. Sanitization cleans or escapes input for a particular use.",
		"A bouncer checking IDs at the door, rather than hoping everyone inside is of age.",
		`age = int(text)
if not 0 <= age <= 150:
    raise ValueError("age out of range")`,
		"Validate on the server, always. Checks in the browser are a convenience that attackers simply skip.",
		[]string{"Injection", "Edge case", "Vulnerability"}},
	{"Authentication", []string{"authn", "authorization", "authz", "login"}, "Security", 10,
		"Authentication proves who you are (password, key, fingerprint). Authorization decides what you are allowed to do once known.",
		"At a hotel, showing your ID at check-in is authentication; your key card opening only your room is authorization.",
		`Logged in as Ada (authn) ✓
Ada may read /reports but not /admin (authz)`,
		"Many breaches are authorization bugs: the user is who they claim to be, but the app forgets to check they own the record.",
		[]string{"Password hashing", "Cookie", "Principle of least privilege"}},
	{"Encryption", []string{"encrypt", "decrypt", "cipher", "plaintext", "ciphertext"}, "Security", 10,
		"Scrambling data with a key so only someone with the right key can read it. Plaintext goes in; ciphertext comes out.",
		"A locked diary: the text is there, but useless without the key.",
		`AES-GCM with a random key: plaintext → ciphertext + authentication tag`,
		"Never invent your own encryption. Use well-reviewed libraries, and remember encoding (Base64) is not encryption.",
		[]string{"Public-key cryptography", "TLS", "Hash function"}},
	{"Public-key cryptography", []string{"public key", "private key", "asymmetric encryption", "SSH key", "digital signature"}, "Security", 10,
		"Cryptography with a key pair: a public key anyone may have, and a private key only you keep. Others encrypt to you or verify your signatures with the public key; only the private key can decrypt or sign.",
		"A mailbox with a slot: anyone can drop a letter in (public key), only the owner has the key to open it (private key).",
		`ssh-keygen -t ed25519      # makes id_ed25519 (private) and id_ed25519.pub (public)`,
		"Share the .pub file; never share the private key, not even with support staff.",
		[]string{"Encryption", "TLS"}},
	{"Password hashing", []string{"salt", "bcrypt", "argon2", "scrypt"}, "Security", 10,
		"Storing passwords as the output of a deliberately slow, salted hash (bcrypt, scrypt, Argon2), never as plain text, so a stolen database does not reveal them. A salt is random data added per user so equal passwords get different hashes.",
		"Keeping only a fingerprint of each key: you can check a key matches, but cannot rebuild the key from the print.",
		`hash = argon2.hash(password)
argon2.verify(hash, attempt)     # True or False`,
		"Fast hashes like SHA-256 are the wrong tool for passwords: attackers can try billions per second.",
		[]string{"Hash function", "Authentication"}},
	{"Principle of least privilege", []string{"least privilege", "sandbox"}, "Security", 10,
		"Give every program, person and key only the permissions it needs, and nothing more, so a mistake or break-in does limited damage.",
		"A hotel cleaner's key opens guest rooms, not the safe.",
		`Run the web server as an unprivileged user, not root.`,
		"Convenience pushes towards \"just give it admin\". Resist; that is how small bugs become disasters.",
		[]string{"Authentication", "Vulnerability"}},
	{"Supply-chain attack", []string{"supply chain", "typosquatting", "malicious package"}, "Security", 10,
		"An attack that compromises software you depend on (a package, a build tool, an update server), so the malicious code reaches you through trusted channels.",
		"Poisoning the flour at the mill instead of breaking into each bakery.",
		`pip install reqeusts    # typo: a look-alike package may be malicious`,
		"Pin versions, check names carefully, and prefer fewer, well-known dependencies.",
		[]string{"Dependency", "Package"}},
	{"Threat model", []string{"threat modeling", "attack surface"}, "Security", 10,
		"A written answer to: what are we protecting, from whom, how could they attack it, and what will we do about it? The attack surface is every way in.",
		"Before buying locks, asking whether you fear burglars, floods or nosy neighbours.",
		`Asset: user passwords. Attacker: remote. Entry: login form. Defence: rate limit + Argon2.`,
		"Security without a threat model is guesswork: you over-protect some things and forget others.",
		[]string{"Vulnerability", "Principle of least privilege"}},
}

var vocabAI = []Word{
	{"Machine learning", []string{"ML", "AI", "artificial intelligence"}, "AI & ML", 14,
		"Programs that learn patterns from examples (data) instead of following hand-written rules. AI is the broader goal of machines doing tasks that seem to need intelligence; ML is today's main way to get there.",
		"Learning to recognise cats by seeing thousands of cat photos, rather than reading a rule book about whiskers.",
		`model.fit(X_train, y_train)
model.predict(X_new)`,
		"ML finds correlations in its data, including the biases and mistakes in it. It does not understand the way people do.",
		[]string{"Model", "Training", "Dataset"}},
	{"Model", []string{"ML model", "neural network", "LLM", "large language model"}, "AI & ML", 15,
		"In machine learning, the mathematical function with adjustable numbers (parameters) that turns inputs into predictions. A neural network is one kind; an LLM is a very large one trained on text.",
		"A mixing desk with millions of knobs, tuned until the output sounds right.",
		`y = w * x + b      # the tiniest model: two parameters, w and b`,
		"\"Model\" in ML is not the same as \"model\" in MVC web frameworks or in database design.",
		[]string{"Parameters", "Training", "Inference"}},
	{"Parameters", []string{"weights", "biases", "weights and biases"}, "AI & ML", 15,
		"The numbers inside a model that training adjusts. A \"7B model\" has about 7 billion of them.",
		"The positions of all the knobs on the mixing desk.",
		`nn.Linear(512, 256)   # 512×256 weights + 256 biases`,
		"More parameters is not automatically better; data quality and training matter as much.",
		[]string{"Model", "Training", "Hyperparameter"}},
	{"Hyperparameter", []string{"learning rate", "batch size", "epoch"}, "AI & ML", 15,
		"A setting you choose before training, rather than one the model learns: learning rate, batch size, number of epochs (full passes over the data), model size.",
		"The oven temperature and baking time, as opposed to what happens to the cake inside.",
		`optimizer = SGD(model.parameters(), lr=0.01)   # lr is a hyperparameter`,
		"Tune hyperparameters on a validation set, never on the test set.",
		[]string{"Parameters", "Training"}},
	{"Training", []string{"train", "fit", "fine-tuning", "fine-tune"}, "AI & ML", 15,
		"Adjusting a model's parameters, example by example, so its predictions get closer to the right answers. Fine-tuning continues training an existing model on a smaller, specific dataset.",
		"Practising free throws: after each miss you adjust your aim slightly.",
		`for x, y in data:
    loss = loss_fn(model(x), y)
    loss.backward()
    optimizer.step()`,
		"Training is expensive and happens once (or rarely); inference is cheap per call but happens constantly.",
		[]string{"Loss function", "Gradient descent", "Inference", "Overfitting"}},
	{"Inference", []string{"prediction", "serving"}, "AI & ML", 16,
		"Using a trained model to make predictions on new inputs. Serving is running inference for many users.",
		"Taking the exam, after all the studying (training) is done.",
		`with torch.no_grad():
    label = model(image).argmax()`,
		"\"Inference\" here means running the model, not logical inference in the philosophy sense.",
		[]string{"Model", "Training", "Latency"}},
	{"Dataset", []string{"training set", "test set", "validation set", "data split"}, "AI & ML", 14,
		"The collection of examples used to train and evaluate a model, split into a training set (to learn from), a validation set (to tune) and a test set (to measure honestly at the end).",
		"Past exam papers: practise on some, and keep one unseen paper for a true mock exam.",
		`X_train, X_test = train_test_split(X, test_size=0.2)`,
		"If test data leaks into training, your score lies. Keep the test set locked away.",
		[]string{"Overfitting", "Training", "Machine learning"}},
	{"Overfitting", []string{"underfitting", "generalization"}, "AI & ML", 14,
		"When a model memorises its training examples, noise included, and does badly on new data. Underfitting is the opposite: too simple to capture the pattern. The goal is generalisation.",
		"A student who memorised the practice answers word for word and fails when the questions change slightly.",
		`training accuracy 99%, test accuracy 60%   → overfitting`,
		"A great training score means little. Always judge on data the model has never seen.",
		[]string{"Dataset", "Training", "Regularization"}},
	{"Regularization", []string{"dropout", "weight decay"}, "AI & ML", 14,
		"Techniques that discourage a model from becoming too complex, to reduce overfitting: penalising large weights (weight decay), randomly switching units off (dropout), or stopping early.",
		"A teacher who marks down answers that are needlessly complicated.",
		`nn.Dropout(p=0.1)
optimizer = AdamW(params, weight_decay=0.01)`,
		"Regularization trades a little training accuracy for better accuracy on new data.",
		[]string{"Overfitting", "Hyperparameter"}},
	{"Loss function", []string{"loss", "cost function", "objective"}, "AI & ML", 15,
		"A number measuring how wrong the model's predictions are. Training tries to make it smaller.",
		"The distance between where your dart landed and the bullseye.",
		`loss = ((prediction - target) ** 2).mean()    # mean squared error`,
		"A low loss on the wrong objective gives a model that is very good at the wrong thing.",
		[]string{"Gradient descent", "Training"}},
	{"Gradient descent", []string{"gradient", "backpropagation", "backprop", "SGD", "optimizer"}, "AI & ML", 15,
		"The method most models learn by: compute the gradient (which direction makes the loss grow fastest, found by backpropagation) and nudge every parameter a small step the opposite way, many times.",
		"Walking down a foggy hill by always stepping in the steepest downhill direction you can feel.",
		`w = w - learning_rate * dloss_dw`,
		"Too large a learning rate overshoots and diverges; too small crawls forever.",
		[]string{"Loss function", "Training", "Hyperparameter"}},
	{"Tensor", []string{"tensors", "matrix", "vector"}, "AI & ML", 13,
		"A multi-dimensional array of numbers: a vector is 1-D, a matrix is 2-D, and tensors go further. Deep-learning libraries do almost everything with tensors.",
		"A spreadsheet (matrix), and then a stack of spreadsheets (3-D tensor), and so on.",
		`x = torch.zeros(32, 3, 224, 224)   # a batch of 32 RGB images`,
		"Most deep-learning bugs are shape mismatches. Print tensor shapes often.",
		[]string{"Model", "Array", "GPU"}},
	{"Embedding", []string{"embeddings", "vector embedding"}, "AI & ML", 15,
		"A list of numbers (a vector) representing something like a word, image or document, arranged so that similar things get nearby vectors.",
		"Placing every city on a map: cities that are alike end up close together.",
		`king - man + woman ≈ queen    # the famous word-vector example`,
		"Similar vectors mean \"used in similar ways in the training data\", not \"true synonyms\".",
		[]string{"Tensor", "Token", "Model"}},
	{"Token", []string{"tokens", "tokenizer", "tokenization"}, "AI & ML", 15,
		"The small pieces of text (whole words, parts of words, or characters) a language model reads and writes. A tokenizer splits text into tokens.",
		"Lego bricks for text: the model builds sentences brick by brick.",
		`"unbelievable" → ["un", "believ", "able"]`,
		"Model limits and prices are counted in tokens, not words; roughly 4 characters of English per token.",
		[]string{"Embedding", "Model", "Context window"}},
	{"Context window", []string{"context length"}, "AI & ML", 16,
		"The maximum number of tokens a language model can consider at once: the prompt plus its answer.",
		"How much of a conversation someone can keep in mind at once.",
		`A 200k-token context window holds roughly a long novel.`,
		"Anything outside the window is invisible to the model, however important.",
		[]string{"Token", "Model"}},
	{"GPU", []string{"graphics card", "CUDA", "accelerator"}, "AI & ML", 16,
		"A processor with thousands of simple cores that work in parallel, first built for graphics and now used for training and running AI models. CUDA is NVIDIA's platform for programming them.",
		"A thousand students each solving one simple sum at once, versus one professor (the CPU) solving hard problems one by one.",
		`model.to("cuda")    # move a PyTorch model to the GPU`,
		"GPUs are fast only on big, parallel, regular work. Moving data to and from them costs time.",
		[]string{"Tensor", "Concurrency", "Bandwidth"}},
}

var vocabCulture = []Word{
	{"Boilerplate", nil, "Jargon & culture", NoStage,
		"Repetitive code you must write almost the same way every time, with little thought in it: setup, imports, getters.",
		"The standard legal small print at the bottom of every contract.",
		`int main(void) { return 0; }   // the boilerplate of every C program`,
		"Lots of boilerplate is a hint that a function, a library or a better tool could help.",
		[]string{"DRY", "Framework"}},
	{"Idiomatic", []string{"idiom", "Pythonic"}, "Jargon & culture", NoStage,
		"Written the way experienced users of a language naturally write it, using its usual style and features.",
		"Speaking a language like a native, not word-for-word translated.",
		`# not idiomatic Python
for i in range(len(items)): print(items[i])
# idiomatic
for item in items: print(item)`,
		"Each language has its own idioms. Good C is not good Python, and vice versa.",
		[]string{"Syntactic sugar", "Code review"}},
	{"Syntactic sugar", nil, "Jargon & culture", 11,
		"Syntax that makes something easier to write or read without adding new power: it could be written a longer way.",
		"Saying \"brunch\" instead of \"a meal between breakfast and lunch\".",
		`x += 1        # sugar for x = x + 1
[x*2 for x in xs]   # sugar for a loop that appends`,
		"Knowing what the sugar expands to helps when it behaves unexpectedly.",
		[]string{"Syntax", "Idiomatic"}},
	{"Hardcode", []string{"hard-coded", "hardcoded"}, "Jargon & culture", NoStage,
		"Writing a fixed value straight into the code instead of reading it from input, configuration or a constant.",
		"Printing a date on a form instead of leaving a blank to fill in.",
		`url = "http://localhost:8080"    # hardcoded: breaks in production`,
		"Hardcoded passwords or keys in source code are a serious security leak once the code is shared.",
		[]string{"Magic number", "Configuration", "Constant"}},
	{"Magic number", []string{"magic string"}, "Jargon & culture", NoStage,
		"An unexplained literal value in code whose meaning is unclear.",
		"A recipe that says \"add 37\" with no unit and no reason.",
		`if status == 3: ...            # what is 3?
if status == STATUS_SHIPPED: ... # clear`,
		"Give magic numbers a name. The next reader (often you) will thank you.",
		[]string{"Constant", "Hardcode", "Enum"}},
	{"Spaghetti code", []string{"big ball of mud"}, "Jargon & culture", 9,
		"Tangled code where everything depends on everything else and the flow is hard to follow.",
		"A bowl of spaghetti: pull one strand and the whole plate moves.",
		`One 2,000-line function full of flags, globals and early returns.`,
		"It rarely starts that way. It grows from many small \"just this once\" shortcuts.",
		[]string{"Technical debt", "Refactoring"}},
	{"Legacy code", []string{"legacy"}, "Jargon & culture", 9,
		"Old code still in use, often written by people who have left, and hard to change safely. Michael Feathers defines it as code without tests.",
		"An old house still lived in, with wiring nobody fully understands.",
		`A 1990s COBOL banking system still processing payments today.`,
		"Legacy code earns money and works. Respect it, add tests around it, then change it.",
		[]string{"Technical debt", "Refactoring", "Test"}},
	{"Hack", []string{"hacky", "kludge"}, "Jargon & culture", NoStage,
		"Either a quick, inelegant fix (a kludge or workaround) or, in the older sense, a clever, playful solution. Context tells you which.",
		"Holding a door shut with a chair (a kludge), versus building a clever doorstop (the older, admiring sense).",
		`# HACK: sleep until the file appears; replace with a proper wait`,
		"Mark hacks with a comment saying why, so they get cleaned up.",
		[]string{"Technical debt", "Workaround"}},
	{"DRY", []string{"don't repeat yourself"}, "Jargon & culture", 9,
		"Don't Repeat Yourself: each piece of knowledge should live in one place, so a change happens once.",
		"Keeping one master copy of an address instead of writing it on twenty sticky notes.",
		`TAX_RATE = 0.2    # used everywhere, defined once`,
		"Two pieces of code that look alike but change for different reasons are not repetition. Merging them too early hurts.",
		[]string{"KISS", "YAGNI", "Refactoring"}},
	{"KISS", []string{"keep it simple"}, "Jargon & culture", 9,
		"Keep It Simple: prefer the simplest design that works.",
		"A spoon instead of a motorised stirring robot.",
		`A plain loop before a clever one-liner nobody can read.`,
		"Simple is not the same as easy. Simple designs often take more thought.",
		[]string{"YAGNI", "DRY"}},
	{"YAGNI", []string{"you aren't gonna need it"}, "Jargon & culture", 9,
		"You Aren't Gonna Need It: do not build features or flexibility until there is a real need for them.",
		"Not buying a twelve-seat dining table \"in case\" you host a banquet one day.",
		`Skip the plugin system until a second use case actually exists.`,
		"YAGNI is about features, not about good practices like tests and clear names.",
		[]string{"KISS", "Premature optimization"}},
	{"Premature optimization", nil, "Jargon & culture", 9,
		"Making code faster before knowing that it is too slow, or where. Knuth wrote that premature optimisation is \"the root of all evil\" (or at least most of it) in programming.",
		"Tuning a car's engine before checking whether you have a flat tyre.",
		`Measure first: python -m cProfile app.py, then optimise the hot spot.`,
		"The full Knuth quote goes on: \"yet we should not pass up our opportunities in that critical 3%\". Measure, then act.",
		[]string{"Big-O notation", "YAGNI"}},
	{"Off-by-one error", []string{"off by one", "OBOE", "fencepost error"}, "Jargon & culture", 2,
		"A bug where a loop or index is one step too many or too few, often from mixing up < and <= or counting from 0 versus 1.",
		"A 10-metre fence with posts every metre needs 11 posts, not 10 (the fencepost problem).",
		`for (int i = 0; i <= n; i++)   // runs n+1 times: off by one
    a[i] = 0;                   // writes past the end`,
		"Check the first and last iterations by hand. That is where these bugs hide.",
		[]string{"Edge case", "Index", "Buffer overflow"}},
	{"Heisenbug", nil, "Jargon & culture", 6,
		"A bug that disappears or changes when you try to observe it (for example when you add prints or use a debugger), often because of timing or uninitialised memory.",
		"A noise in your car that stops the moment the mechanic listens.",
		`A race condition that vanishes when print statements slow the threads down.`,
		"Heisenbugs are usually race conditions or undefined behaviour. Reach for -race and sanitizers.",
		[]string{"Race condition", "Undefined behavior", "Debugging"}},
	{"Rubber duck debugging", []string{"rubber ducking"}, "Jargon & culture", 1,
		"Explaining your code line by line out loud, even to a rubber duck, until you hear yourself say the mistake. From The Pragmatic Programmer.",
		"Realising the answer while writing the email asking for help, before you press send.",
		`"…and then this loop runs until i equals n… oh. It should stop before n."`,
		"It works because explaining forces you to check each assumption instead of skimming.",
		[]string{"Debugging", "Feynman technique"}},
	{"Feynman technique", nil, "Jargon & culture", NoStage,
		"A learning method named after physicist Richard Feynman: explain an idea in plain words as if to a beginner, find the gaps where you stumble, study those, and simplify again.",
		"Teaching a child how a bicycle stays upright, and discovering which part you cannot actually explain.",
		`Write "Type casting means…" in two sentences with no jargon.`,
		"If you can only repeat the textbook's words, you have memorised, not understood. This academy's \"In your own words\" notes use this idea.",
		[]string{"Rubber duck debugging"}},
	{"Yak shaving", nil, "Jargon & culture", NoStage,
		"A chain of seemingly unrelated tasks you must finish before the task you actually wanted to do.",
		"To fix the tap you need a wrench, which is at your neighbour's, who wants their pillow back first, which needs yak hair…",
		`Fix a typo → the build fails → update the compiler → upgrade the OS…`,
		"Notice when you are yak shaving and ask whether a shortcut or a different route exists.",
		[]string{"Bikeshedding"}},
	{"Bikeshedding", []string{"bike-shedding", "law of triviality"}, "Jargon & culture", NoStage,
		"Spending far too long on trivial, easy-to-discuss details while ignoring the hard, important ones. From Parkinson's example of a committee debating a bike shed instead of a nuclear plant.",
		"Arguing about the colour of the invitations while the venue is still not booked.",
		`A two-hour review thread about tabs versus spaces.`,
		"Formatters and style guides exist partly to end bikeshedding.",
		[]string{"Formatter", "Yak shaving"}},
	{"Footgun", []string{"foot-gun", "shoot yourself in the foot"}, "Jargon & culture", 5,
		"A feature that makes it very easy to hurt yourself by accident.",
		"A kitchen knife without a handle.",
		`gets(buf);    // C: no size limit; removed from the language for good reason
rm -rf / tmp  // one stray space`,
		"C has many footguns. Being bulletproof in C means knowing every one by name and avoiding them on purpose.",
		[]string{"Undefined behavior", "Buffer overflow"}},
	{"Happy path", []string{"sad path", "golden path"}, "Jargon & culture", 9,
		"The route through a program when everything goes right: valid input, no errors. The sad paths are everything else.",
		"A trip where every train is on time.",
		`Happy: valid login. Sad: wrong password, locked account, server down, empty field.`,
		"Programs are judged by how they handle the sad paths. Test those.",
		[]string{"Edge case", "Test", "Exception"}},
	{"Dogfooding", []string{"eat your own dog food"}, "Jargon & culture", 9,
		"Using your own product yourself, day to day, to find its problems before users do.",
		"A chef who eats at their own restaurant every night.",
		`Building this academy's notes while studying with the academy.`,
		"If you would not use it, ask why anyone else should.",
		[]string{"Test"}},
	{"Cargo cult programming", []string{"cargo cult"}, "Jargon & culture", NoStage,
		"Copying code or rituals without understanding why they work, hoping for the same result.",
		"Copying a chef's hand gestures without learning why they add salt at that moment.",
		`Pasting a Stack Overflow answer with a sleep(2) "because it fixed it for them".`,
		"The cure is the whole point of this academy: understand each line you use.",
		[]string{"Idiomatic", "Documentation"}},
	{"Workaround", nil, "Jargon & culture", NoStage,
		"A way to get something working despite a bug or limitation, without fixing the underlying cause.",
		"Using the back door because the front lock is jammed.",
		`# Workaround for issue #123: retry once on timeout`,
		"Record why a workaround exists and when it can be removed.",
		[]string{"Hack", "Technical debt"}},
	{"TL;DR", []string{"tldr", "too long; didn't read"}, "Jargon & culture", NoStage,
		"\"Too long; didn't read\": a one-line summary at the top or bottom of a long text.",
		"The headline of a newspaper article.",
		`TL;DR: use parameterised queries; never concatenate SQL.`,
		"Writing a good TL;DR forces you to know your main point.",
		[]string{"Documentation"}},
	{"LGTM", []string{"looks good to me", "nit", "PTAL", "WIP"}, "Jargon & culture", 9,
		"Code-review shorthand. LGTM: looks good to me (approved). nit: a tiny, optional suggestion. PTAL: please take another look. WIP: work in progress, not ready yet.",
		"The margin notes an editor scribbles on a draft.",
		`nit: rename tmp to user_count.  Otherwise LGTM!`,
		"An LGTM is a shared responsibility, not a rubber stamp. Read the diff.",
		[]string{"Pull request", "Diff"}},
	{"RTFM", []string{"read the manual"}, "Jargon & culture", NoStage,
		"\"Read the (fine) manual\": a blunt reminder to check the documentation before asking. Old Unix culture.",
		"\"Have you tried the instructions in the box?\"",
		`man 3 printf     # the manual page for C's printf`,
		"The kind version of RTFM is a link to the exact page. Be the kind version.",
		[]string{"Documentation"}},
	{"Unix philosophy", []string{"do one thing well"}, "Jargon & culture", 6,
		"A design tradition from Bell Labs: write programs that do one thing well, work together through text streams, and can be combined.",
		"A set of good kitchen knives, each for one job, instead of one gadget that does everything badly.",
		`sort names.txt | uniq -c | sort -rn | head`,
		"Small composable tools beat one giant tool, until the glue between them becomes the problem.",
		[]string{"Pipe", "KISS"}},
	{"Lindy effect", nil, "Jargon & culture", NoStage,
		"The idea that the longer a non-perishable thing (a technology, a book, an idea) has survived, the longer it is likely to survive. C (1972), Unix, SQL and TCP/IP are Lindy; this year's framework may not be.",
		"A restaurant that has thrived for 50 years is a safer bet than one that opened last month.",
		`Learn C, SQL, HTTP and algorithms first; frameworks second.`,
		"This is why the academy puts fundamentals before trends, and why tech watch focuses on what builds on them.",
		[]string{"Tech watch", "Hype cycle"}},
	{"Hype cycle", []string{"hype", "peak of inflated expectations", "trough of disillusionment"}, "Jargon & culture", NoStage,
		"Gartner's model of how new technologies are received: a trigger, a peak of inflated expectations, a trough of disillusionment, then a slow slope to real productivity.",
		"A new diet craze: everyone swears by it, then everyone hates it, then people quietly keep the parts that work.",
		`"X will replace all programmers within a year" → peak
"X is useless" → trough
"X is a good tool for Y" → productivity`,
		"Gartner's curve is a descriptive model, not a law. It is still a useful reminder not to believe the peak.",
		[]string{"Tech watch", "Lindy effect", "Technology radar"}},
	{"Tech watch", []string{"technology watch", "technology monitoring", "veille technologique", "keeping up"}, "Jargon & culture", NoStage,
		"The habit of regularly and deliberately following what changes in your field (releases, papers, security advisories, practices), filtering signal from noise, and deciding what to learn or try. The academy's tech watch screen [w] teaches a method.",
		"A ship's lookout: scanning the horizon on a schedule, reporting what matters, ignoring the gulls.",
		`Weekly: 30 min skimming feeds → save 3 items → read 1 deeply → write why it matters → try 1 thing.`,
		"Tech watch is not endless scrolling. Without triage and notes, it is just entertainment.",
		[]string{"Technology radar", "Hype cycle", "Lindy effect"}},
	{"Technology radar", []string{"tech radar", "adopt trial assess hold"}, "Jargon & culture", NoStage,
		"A way to record technology decisions in four rings: Adopt (use it), Trial (use it on something real but low-risk), Assess (explore it), Hold (do not start with it now). Popularised by Thoughtworks.",
		"A traffic light for technologies, with an extra \"worth a look\" colour.",
		`Adopt: Git, PostgreSQL · Trial: a new test runner · Assess: a new language · Hold: an abandoned library`,
		"Your radar is personal: it reflects your goals and context, not what is popular.",
		[]string{"Tech watch", "Hype cycle"}},
}
