package main

// Dictionary: memory & C, tools & workflow, systems & concurrency,
// networks & web, data & databases.

var vocabMemory = []Word{
	{"Memory", []string{"RAM", "main memory"}, "Memory & C", 5,
		"Where a running program keeps its data: a huge row of numbered bytes (RAM). It is fast but temporary, and is wiped when the power goes off.",
		"A desk: you work on it quickly, but it is cleared every evening. Storage (disk) is the filing cabinet.",
		`int x = 5;    // x lives somewhere in memory, at some address`,
		"Memory (RAM) and storage (disk or SSD) are different. \"Out of memory\" does not mean the disk is full.",
		[]string{"Memory address", "Stack", "Heap", "Cache"}},
	{"Memory address", []string{"address"}, "Memory & C", 5,
		"The number that identifies one byte's location in memory. Every variable lives at some address.",
		"A house number on a very long street where every house holds one byte.",
		`int x = 5;
printf("%p", (void *)&x);   // prints something like 0x7ffd5e8c`,
		"Addresses change between runs. Never save one to a file and expect it to mean anything later.",
		[]string{"Pointer", "Memory", "Hexadecimal"}},
	{"Pointer", []string{"pointers"}, "Memory & C", 5,
		"A variable that holds a memory address, so it \"points to\" another value. Central to C: you can pass big data around cheaply by passing where it is.",
		"A note that says \"the treasure is in locker 42\", instead of the treasure itself.",
		`int x = 5;
int *p = &x;     // p points to x
*p = 7;          // changes x through the pointer`,
		"The * in a declaration (int *p) says \"p is a pointer\"; the * in an expression (*p) means \"go to the address\". Same symbol, two jobs.",
		[]string{"Dereference", "Memory address", "Null pointer", "Reference"}},
	{"Dereference", []string{"dereferencing"}, "Memory & C", 5,
		"Following a pointer to the value it points to.",
		"Actually walking to locker 42 and opening it.",
		`int *p = &x;
int y = *p;     // dereference: read the value at p
p->field        // dereference and pick a struct field`,
		"Dereferencing a null or freed pointer is one of the most common crashes in C.",
		[]string{"Pointer", "Null pointer", "Segmentation fault"}},
	{"Reference", []string{"pass by reference", "pass by value"}, "Memory & C", 5,
		"A way to refer to a value without copying it. \"Pass by value\" gives a function a copy; \"pass by reference\" lets it reach the original.",
		"Giving someone a photocopy of a document (value) or the link to the shared original (reference).",
		`void inc(int *n) { (*n)++; }   // C: pass a pointer to change the caller's int
inc(&count);`,
		"Python passes references to objects: a function can change your list, but reassigning the parameter does not affect you.",
		[]string{"Pointer", "Mutable", "Side effect"}},
	{"Stack", []string{"call stack", "stack frame"}, "Memory & C", 5,
		"The region of memory that holds each active function call's local variables. Each call pushes a \"frame\"; returning pops it. Fast and automatic, but limited in size.",
		"A stack of trays in a canteen: you always add and remove at the top.",
		`void f(void) {
    int local = 3;   // lives on the stack, gone when f returns
}`,
		"Returning a pointer to a local variable is a bug: its stack frame is gone after the return. \"Stack\" is also the name of a data structure (last in, first out).",
		[]string{"Heap", "Stack overflow", "Recursion", "Stack trace"}},
	{"Heap", []string{"heap memory", "dynamic memory"}, "Memory & C", 5,
		"The region of memory for data that must outlive a single function call, or whose size is known only at runtime. In C you request it with malloc and give it back with free.",
		"A self-storage warehouse: you rent a unit for as long as you need, and you must return the key.",
		`int *nums = malloc(100 * sizeof(int));
/* ... use nums ... */
free(nums);`,
		"This heap is unrelated to the heap data structure (priority queue), despite the shared name.",
		[]string{"Stack", "Malloc and free", "Memory leak", "Garbage collection"}},
	{"Malloc and free", []string{"malloc", "free", "allocation", "allocate", "deallocate"}, "Memory & C", 5,
		"C's functions for manual memory management: malloc(n) reserves n bytes on the heap and returns a pointer; free(p) gives them back.",
		"Checking a book out of the library (malloc) and returning it (free). Keep it forever and nobody else can use it.",
		`char *buf = malloc(64);
if (buf == NULL) return -1;   // malloc can fail
strcpy(buf, "hi");
free(buf);
buf = NULL;                   // avoid a dangling pointer`,
		"Every malloc needs exactly one free: none is a leak, two is a crash or worse.",
		[]string{"Heap", "Memory leak", "Dangling pointer", "Use-after-free"}},
	{"Memory leak", []string{"leak"}, "Memory & C", 5,
		"Memory a program allocated but never released, so it slowly uses more and more until it slows down or crashes.",
		"Leaving the tap running in every room you visit.",
		`for (;;) {
    char *s = malloc(1024);   // never freed: leaks 1 KB per loop
}`,
		"Garbage-collected languages can leak too, by keeping references to things they no longer need.",
		[]string{"Malloc and free", "Garbage collection", "Heap"}},
	{"Dangling pointer", []string{"use-after-free", "use after free"}, "Memory & C", 5,
		"A pointer that still holds the address of memory that has been freed or has gone out of scope. Using it (\"use-after-free\") is undefined behaviour and a classic security hole.",
		"Keeping the key to a hotel room after you have checked out. The room now belongs to someone else.",
		`char *p = malloc(8);
free(p);
p[0] = 'x';     // use-after-free: undefined behaviour`,
		"Setting a pointer to NULL after freeing it turns a silent corruption into an obvious crash.",
		[]string{"Pointer", "Malloc and free", "Undefined behavior", "Memory safety"}},
	{"Null pointer", []string{"NULL pointer", "nil pointer", "null dereference"}, "Memory & C", 5,
		"A pointer that points to nothing (NULL). Dereferencing it usually crashes the program.",
		"A locker note that says \"no locker\". Trying to open it gets you nowhere.",
		`int *p = NULL;
if (p != NULL) *p = 1;    // always check first`,
		"Many functions return NULL to signal failure (malloc, fopen). Check before using the result.",
		[]string{"Null", "Pointer", "Segmentation fault"}},
	{"Buffer", nil, "Memory & C", 5,
		"A block of memory used to hold data temporarily, often while it moves between places (from a file, a network or a keyboard).",
		"A bucket that collects water from a slow tap before you pour it into a pot.",
		`char line[256];                  // a 256-byte buffer
fgets(line, sizeof line, stdin); // safe: never writes more than 256`,
		"A buffer has a fixed size. Writing past its end is a buffer overflow.",
		[]string{"Buffer overflow", "Array", "Stream"}},
	{"Buffer overflow", []string{"overflow bug", "out of bounds", "out-of-bounds"}, "Memory & C", 10,
		"Writing more data into a buffer than it can hold, so the extra bytes overwrite whatever sits next to it in memory. One of the most exploited bugs in history.",
		"Pouring two litres into a one-litre jug: it spills onto everything nearby.",
		`char name[8];
strcpy(name, user_input);          // overflow if input > 7 chars
snprintf(name, sizeof name, "%s", user_input);   // bounded: safe`,
		"C does not check array bounds for you. Always pass and respect sizes, and prefer bounded functions.",
		[]string{"Buffer", "Undefined behavior", "Memory safety", "Vulnerability"}},
	{"Segmentation fault", []string{"segfault", "SIGSEGV", "access violation"}, "Memory & C", 6,
		"The crash you get when a program touches memory it is not allowed to, such as a null pointer or an address far outside its memory. The operating system stops it.",
		"A security guard stopping you at a door your badge does not open.",
		`int *p = NULL;
*p = 1;         // Segmentation fault (core dumped)`,
		"A segfault is the lucky case: the bug was caught. Many memory bugs corrupt data silently instead.",
		[]string{"Null pointer", "Dangling pointer", "Virtual memory"}},
	{"Undefined behavior", []string{"UB", "undefined behaviour"}, "Memory & C", 5,
		"Operations the C standard gives no meaning to, such as reading past an array, using freed memory, or overflowing a signed int. The program may crash, seem to work, or do something bizarre, and the compiler is allowed to assume it never happens.",
		"A board game rule book that says \"if you do this, anything may happen\", and some players then take it literally.",
		`int a[4];
a[4] = 1;          // UB: the index 4 is out of bounds
int i = INT_MAX;
i++;               // UB: signed overflow`,
		"\"It works on my machine\" proves nothing for undefined behaviour. Use -Wall -Wextra and sanitizers (-fsanitize=address,undefined).",
		[]string{"Buffer overflow", "Integer overflow", "Memory safety", "Compiler"}},
	{"Memory safety", []string{"memory-safe", "memory safe"}, "Memory & C", 10,
		"A guarantee that a program cannot read or write memory it should not: no buffer overflows, no use-after-free. Python, Go, Java and Rust are memory-safe by default; C and C++ are not.",
		"A kitchen with guards on every knife, versus one where you are trusted to be careful.",
		`// C lets this compile and run:
char s[4]; s[10] = 'x';
// Rust or Go refuses or panics safely instead`,
		"Being \"bulletproof like C\" means knowing C deeply and writing it defensively. C itself gives you power, not protection.",
		[]string{"Buffer overflow", "Dangling pointer", "Undefined behavior", "Garbage collection"}},
	{"Garbage collection", []string{"garbage collector", "GC"}, "Memory & C", 5,
		"Automatic memory management: the runtime finds data nothing refers to any more and frees it for you. Python, Java, Go and JavaScript have it; C does not.",
		"A cleaner who throws away anything nobody has touched, so you never have to take out the rubbish.",
		`items = [1, 2, 3]
items = None      # the old list is now garbage; the GC frees it`,
		"GC prevents most leaks and dangling pointers, but costs some CPU time and occasional pauses.",
		[]string{"Heap", "Memory leak", "Malloc and free"}},
	{"Header file", []string{"header", ".h file", "#include"}, "Memory & C", 5,
		"In C, a .h file that declares functions, types and constants so other files can use them. #include pastes it in before compiling.",
		"A restaurant's menu (declarations) posted outside, while the kitchen (the .c file) makes the food.",
		`#include <stdio.h>     // declares printf
#include "list.h"      // your own header`,
		"Headers should declare things, not define them. A definition in a header included twice breaks the build.",
		[]string{"Preprocessor", "Linker", "Compiler"}},
	{"Preprocessor", []string{"macro", "#define"}, "Memory & C", 5,
		"C's first build step: it handles lines starting with #, pasting in headers, replacing macros and removing code that is switched off, all before real compilation.",
		"A copy editor who does find-and-replace on the manuscript before the printer sees it.",
		`#define SQUARE(x) ((x) * (x))
SQUARE(3)     // becomes ((3) * (3))`,
		"Macros are plain text substitution: SQUARE(i++) increments i twice. Prefer inline functions and constants.",
		[]string{"Header file", "Compiler"}},
	{"Compiler", []string{"compile", "compilation", "gcc", "clang"}, "Memory & C", 5,
		"A program that translates source code into machine code (or another lower-level form) before the program runs. gcc and clang compile C; go build compiles Go.",
		"A translator who translates a whole book before it is published.",
		`gcc -Wall -Wextra -O2 -o hello hello.c
./hello`,
		"Turn warnings on (-Wall -Wextra) and read them. A warning is the compiler pointing at a likely bug for free.",
		[]string{"Interpreter", "Linker", "Machine code", "Compile time"}},
	{"Interpreter", []string{"interpreted"}, "Memory & C", 5,
		"A program that runs source code (or bytecode) directly, reading and executing it as it goes, instead of producing a standalone executable first. CPython is an interpreter.",
		"A live interpreter at a meeting, translating each sentence as it is spoken.",
		`python3 script.py    # the interpreter reads and runs script.py`,
		"\"Compiled vs interpreted\" describes implementations, not languages: Python can be compiled and C can be interpreted.",
		[]string{"Compiler", "Bytecode", "Runtime"}},
	{"Bytecode", nil, "Memory & C", 5,
		"An intermediate, compact instruction format for a virtual machine, not for a real CPU. Python, Java and WebAssembly use bytecode.",
		"Shorthand notes a translator makes: faster to read aloud than the original, but still not the final speech.",
		`import dis
dis.dis(lambda x: x + 1)   # shows Python's bytecode`,
		"Python's .pyc files are cached bytecode, not machine code.",
		[]string{"Interpreter", "Virtual machine", "Machine code"}},
	{"Machine code", []string{"native code", "object code"}, "Memory & C", 4,
		"The raw binary instructions a CPU executes directly. Compilers produce it; humans almost never write it by hand.",
		"The electrical signals that actually move a piano's hammers, below the sheet music.",
		`B8 2A 00 00 00     # x86 machine code for "mov eax, 42"`,
		"Machine code is specific to a CPU family: x86 code does not run on an ARM chip without translation.",
		[]string{"Assembly", "Compiler", "Executable"}},
	{"Assembly", []string{"assembly language", "asm", "assembler"}, "Memory & C", 4,
		"A human-readable text form of machine code, one line per CPU instruction. An assembler turns it into machine code.",
		"Machine code with name tags on every instruction.",
		`mov eax, 42     ; put 42 in register eax
ret             ; return`,
		"You rarely write assembly, but reading it (for example on Compiler Explorer) shows what your code really does.",
		[]string{"Machine code", "Register", "Compiler"}},
	{"Register", []string{"CPU register"}, "Memory & C", 4,
		"A tiny, extremely fast storage slot inside the CPU itself, holding the values it is working on right now.",
		"The few things in your hands while cooking, as opposed to the fridge (memory).",
		`add eax, ebx    ; add two registers`,
		"A CPU has only a few dozen registers; the compiler decides which variables live in them.",
		[]string{"Assembly", "Cache", "Memory"}},
	{"Linker", []string{"linking", "link error", "undefined reference"}, "Memory & C", 5,
		"The build step that joins separately compiled pieces and libraries into one executable, connecting each function call to where the function actually is.",
		"The bookbinder who gathers every chapter and builds the table of contents so page references work.",
		`gcc main.o list.o -o app
undefined reference to 'list_add'   // a linker error: declared but never defined`,
		"\"Undefined reference\" is a linker error, not a compiler error: the declaration was found, the code was not.",
		[]string{"Compiler", "Header file", "Executable"}},
	{"Executable", []string{"binary file", "exe", "program file"}, "Memory & C", 5,
		"A file the operating system can run directly, like app.exe or ./academy, usually produced by a compiler and linker.",
		"A ready-to-eat meal, as opposed to the recipe (source) and the ingredients.",
		`go build -o academy .    # produces the executable ./academy`,
		"On Unix a file also needs execute permission (chmod +x) to run.",
		[]string{"Compiler", "Linker", "Machine code", "Build"}},
	{"Virtual machine", []string{"VM", "virtualization"}, "Memory & C", 6,
		"Either a program that runs bytecode (the Java VM, Python's VM), or software that pretends to be a whole computer so you can run another operating system inside yours.",
		"A flight simulator: a convincing pretend cockpit running inside a real building.",
		`java Main          # the JVM runs Main's bytecode
VirtualBox, QEMU   # whole-computer virtual machines`,
		"The two meanings are unrelated; context tells you which one.",
		[]string{"Bytecode", "Container", "Operating system"}},
}

var vocabTools = []Word{
	{"Terminal", []string{"shell", "command line", "console", "CLI", "bash", "zsh", "prompt"}, "Tools & workflow", 9,
		"A text window where you type commands. The shell (bash, zsh, PowerShell) is the program inside it that reads and runs them. A CLI is a program used that way, like this academy.",
		"Texting instructions to your computer instead of pointing and clicking.",
		`ls           # list files
cd projects  # change directory
./academy    # run a program`,
		"The terminal is the window; the shell is the program interpreting what you type.",
		[]string{"Path", "Environment variable", "Standard input and output"}},
	{"Path", []string{"file path", "absolute path", "relative path", "PATH", "working directory"}, "Tools & workflow", 9,
		"Where a file lives, written as folders separated by / (or \\ on Windows). Absolute paths start from the root; relative paths start from the current (working) directory. $PATH is also the list of folders the shell searches for programs.",
		"A postal address (absolute) versus \"two doors down from here\" (relative).",
		`/home/ada/notes.txt     # absolute
../data/input.csv        # relative: up one folder, then into data`,
		"A relative path depends on where you run the program from, a common cause of \"file not found\".",
		[]string{"Terminal", "Environment variable"}},
	{"Environment variable", []string{"env var", "environment"}, "Tools & workflow", 9,
		"A named setting that the shell passes to every program it starts, like HOME, PATH or NO_COLOR.",
		"A note taped to the fridge that everyone in the house can read.",
		`export NO_COLOR=1     # set it (bash/zsh)
echo $HOME            # read it
os.environ["HOME"]    # read it in Python`,
		"Environment variables are inherited by child processes, never passed back up to the parent.",
		[]string{"Terminal", "Process", "Configuration"}},
	{"Standard input and output", []string{"stdin", "stdout", "stderr", "standard input", "standard output", "standard error"}, "Tools & workflow", 6,
		"Every program starts with three streams: stdin (input, usually the keyboard), stdout (normal output, usually the screen) and stderr (error messages).",
		"A worker's in-tray, out-tray and complaints box.",
		`print("result")                 # stdout
print("oops", file=sys.stderr)  # stderr
./app < in.txt > out.txt        # redirect stdin and stdout`,
		"Errors go to stderr so they still show up when stdout is redirected into a file.",
		[]string{"Pipe", "Stream", "File descriptor"}},
	{"Pipe", []string{"|", "pipeline"}, "Tools & workflow", 6,
		"Connecting one program's output directly to another program's input with |, so small tools combine into bigger ones.",
		"A bucket brigade: each person does one job and passes the bucket on.",
		`cat log.txt | grep ERROR | wc -l     # count error lines`,
		"This \"small tools that do one thing, joined by pipes\" idea is the heart of the Unix philosophy.",
		[]string{"Standard input and output", "Terminal", "Process"}},
	{"Exit code", []string{"exit status", "return code"}, "Tools & workflow", 6,
		"The number a program returns to the shell when it ends: 0 means success, anything else means an error.",
		"A thumbs-up (0) or thumbs-down (1–255) given as you leave the room.",
		`./academy -check-links
echo $?          # prints the exit code of the last command`,
		"Scripts and CI rely on exit codes. A program that prints an error but exits with 0 fools them.",
		[]string{"Process", "Continuous integration"}},
	{"Git", []string{"version control", "VCS", "source control"}, "Tools & workflow", 9,
		"The most widely used version control system. It records snapshots of your project over time, so you can go back, compare, and work in parallel with others.",
		"Unlimited save points in a video game, plus the ability to explore alternate storylines and merge them.",
		`git init
git add notes.md
git commit -m "Add notes"
git log`,
		"Git is a tool on your computer; GitHub and GitLab are websites that host Git repositories.",
		[]string{"Repository", "Commit", "Branch", "Merge"}},
	{"Repository", []string{"repo"}, "Tools & workflow", 9,
		"A project folder tracked by version control, including its full history.",
		"A book together with every draft it has ever had.",
		`git clone https://github.com/user/project.git`,
		"Cloning copies the whole history, not just the latest files.",
		[]string{"Git", "Commit"}},
	{"Commit", []string{"git commit"}, "Tools & workflow", 9,
		"A saved snapshot of the project in Git, with a message explaining the change. (In databases, committing makes a transaction permanent; in this academy, Commit saves your registry.)",
		"A dated, labelled photo of your work at one moment.",
		`git commit -m "Fix off-by-one in pagination"`,
		"Small commits with clear messages (\"why\", not just \"what\") make history useful. \"Fixed stuff\" does not.",
		[]string{"Git", "Diff", "Transaction"}},
	{"Branch", []string{"git branch"}, "Tools & workflow", 9,
		"A separate line of development in Git, so you can work on something without disturbing the main version.",
		"A parallel draft of an essay where you try a new ending.",
		`git switch -c try-new-parser
# ...commit experiments...
git switch main`,
		"A branch is cheap in Git: just a movable label on a commit.",
		[]string{"Merge", "Pull request", "Git"}},
	{"Merge", []string{"merge conflict", "rebase"}, "Tools & workflow", 9,
		"Combining the changes from one branch into another. A merge conflict happens when both changed the same lines and Git needs you to choose.",
		"Two editors changed the same sentence; someone has to decide the final wording.",
		`git merge feature
<<<<<<< HEAD ... ======= ... >>>>>>> feature   # conflict markers`,
		"Conflicts are normal, not failures. Read both sides and keep what is correct.",
		[]string{"Branch", "Pull request", "Diff"}},
	{"Pull request", []string{"PR", "merge request", "MR", "code review", "review"}, "Tools & workflow", 9,
		"A request to merge your branch into someone's project, with a page where others review the changes and comment before they are accepted.",
		"Submitting an article to an editor, who marks it up before publishing.",
		`Open a PR from "fix-typo" into "main", reviewers comment, you push fixes, it is merged.`,
		"Code review is about the code, not the person. Small PRs get better reviews.",
		[]string{"Branch", "Merge", "Diff", "LGTM"}},
	{"Diff", []string{"patch"}, "Tools & workflow", 9,
		"The line-by-line difference between two versions of a file: lines removed (-) and added (+). A patch is a diff you can apply.",
		"A \"track changes\" view of a document.",
		`- total = price * qty
+ total = price * qty + shipping`,
		"Reviewing your own diff before committing catches embarrassing mistakes.",
		[]string{"Commit", "Pull request"}},
	{"IDE", []string{"integrated development environment", "editor", "code editor"}, "Tools & workflow", 9,
		"A program for writing code that bundles an editor, file browser, debugger, test runner and more (VS Code, IntelliJ, Vim with plugins).",
		"A workshop with every tool on the wall, instead of a single hammer.",
		`Go to definition, rename symbol, run tests, set breakpoints`,
		"Learn your editor's shortcuts; they pay back every day. But know how to work from a plain terminal too.",
		[]string{"Linter", "Debugging", "Terminal"}},
	{"Linter", []string{"lint", "static analysis"}, "Tools & workflow", 9,
		"A tool that reads your code without running it and flags likely bugs, suspicious patterns and style problems.",
		"A spell- and grammar-checker for code.",
		`go vet ./...
ruff check .
gcc -Wall -Wextra`,
		"Warnings are cheap bug reports. Fix them instead of silencing them.",
		[]string{"Formatter", "Compiler", "Code review"}},
	{"Formatter", []string{"gofmt", "prettier", "black"}, "Tools & workflow", 9,
		"A tool that rewrites code into one consistent layout automatically, so nobody argues about spacing.",
		"A typesetter who makes every page of a book use the same margins and fonts.",
		`gofmt -w .
black app.py`,
		"Formatting is not linting: a perfectly formatted program can still be wrong.",
		[]string{"Linter", "Bikeshedding"}},
	{"Test", []string{"unit test", "testing", "test suite", "integration test", "assertion", "assert"}, "Tools & workflow", 9,
		"Code that checks other code works. A unit test checks one small piece in isolation; an integration test checks pieces working together. An assertion is the check itself.",
		"A smoke detector's test button: press it regularly to make sure it still works.",
		`def test_area():
    assert area(3, 4) == 12
go test ./...`,
		"Tests show the presence of bugs, never their absence (Dijkstra). Test the edge cases, not only the happy path.",
		[]string{"Edge case", "Continuous integration", "Refactoring", "Test-driven development"}},
	{"Test-driven development", []string{"TDD", "red green refactor"}, "Tools & workflow", 9,
		"A habit of writing a failing test first, then the smallest code that makes it pass, then tidying up, in short cycles.",
		"Writing the exam question before you study the answer, so you know exactly what \"done\" means.",
		`1. write test_parse_empty()  → fails (red)
2. make parse("") work       → passes (green)
3. clean up                  → still passes (refactor)`,
		"TDD is a discipline, not a law. It shines for logic with clear inputs and outputs.",
		[]string{"Test", "Refactoring"}},
	{"Refactoring", []string{"refactor"}, "Tools & workflow", 9,
		"Changing code's structure to make it clearer or easier to change, without changing what it does.",
		"Reorganising a messy kitchen: same food, easier to cook in.",
		`Extract a repeated block into a function; rename x to user_count.`,
		"Refactor with tests in place, in small steps, and never mixed with behaviour changes in one commit.",
		[]string{"Technical debt", "Test", "Spaghetti code"}},
	{"Technical debt", []string{"tech debt"}, "Tools & workflow", 9,
		"The future cost of shortcuts taken today: quick fixes and messy code make every later change slower, like interest on a loan.",
		"Shoving everything into a cupboard to tidy fast. It works today, and finding anything costs you later.",
		`# TODO: this only handles one currency; fix before launch`,
		"Some debt is a sensible trade-off. Trouble starts when nobody tracks it or pays it back.",
		[]string{"Refactoring", "Legacy code", "Hack"}},
	{"Build", []string{"build system", "make", "Makefile", "build artifact"}, "Tools & workflow", 9,
		"Turning source code into something runnable or shippable: compiling, linking, bundling. A build system (make, go build, cargo) automates the steps.",
		"The assembly line that turns parts into a finished car.",
		`make
go build -o academy .`,
		"\"It builds\" means it compiles, not that it works. That is what tests are for.",
		[]string{"Compiler", "Continuous integration", "Executable"}},
	{"Continuous integration", []string{"CI", "CI/CD", "pipeline (CI)", "continuous delivery"}, "Tools & workflow", 9,
		"A service that automatically builds and tests every change pushed to a repository, and often deploys it (CD) if everything passes.",
		"A quality inspector who checks every item coming off the line, not just one a week.",
		`push → CI runs go vet, go test → green check or red cross on the PR`,
		"A red CI run is information, not an insult. Read the log from the first error.",
		[]string{"Test", "Build", "Pull request", "Deploy"}},
	{"Deploy", []string{"deployment", "release", "ship", "production", "prod"}, "Tools & workflow", 9,
		"Putting a new version of software where real users use it (\"production\" or \"prod\").",
		"Moving a play from rehearsals to opening night.",
		`Build → test → deploy to staging → deploy to production`,
		"Test in an environment like production (\"staging\") first. \"Works on my machine\" is not a deployment plan.",
		[]string{"Continuous integration", "Rollback"}},
	{"Rollback", []string{"roll back", "revert"}, "Tools & workflow", 9,
		"Undoing a deployment or change by going back to the previous working version.",
		"The undo button, at the scale of a whole release.",
		`git revert <commit>      # a new commit that undoes an old one
./academy -restore 1     # this app's own rollback`,
		"Make rollback easy before you need it: backups nobody has tested may not work.",
		[]string{"Deploy", "Backup"}},
	{"Semantic versioning", []string{"semver", "version number", "major.minor.patch"}, "Tools & workflow", 9,
		"A convention for version numbers MAJOR.MINOR.PATCH: bump MAJOR for breaking changes, MINOR for new features that do not break anything, PATCH for bug fixes.",
		"Editions of a textbook: a new edition may change chapter numbers; a reprint just fixes typos.",
		`1.4.2 → 1.4.3   bug fix
1.4.3 → 1.5.0   new feature
1.5.0 → 2.0.0   breaking change`,
		"Version 0.x.y means \"anything may still change\".",
		[]string{"Deprecated", "API", "Dependency"}},
	{"Deprecated", []string{"deprecation"}, "Tools & workflow", 9,
		"Still working, but officially discouraged and likely to be removed in a future version. Use the recommended replacement.",
		"A shop sign saying \"This entrance will close next month, please use the side door\".",
		`DeprecationWarning: datetime.utcnow() is deprecated`,
		"Deprecation warnings are advance notice. Fix them while it is easy, not when the old way disappears.",
		[]string{"Semantic versioning", "API", "Legacy code"}},
	{"Documentation", []string{"docs", "README", "man page"}, "Tools & workflow", 9,
		"Written explanations of how to use or understand software: READMEs, reference pages, man pages, tutorials and comments.",
		"The instruction manual in the box.",
		`man ls           # the manual page for ls
go doc strings   # Go package docs
help(str)        # Python`,
		"Reading official documentation first is the habit that separates strong programmers from copy-pasters.",
		[]string{"Comment", "API"}},
	{"Stack trace", []string{"traceback", "backtrace", "stacktrace"}, "Tools & workflow", 1,
		"The list of function calls that were active when an error happened, from the outermost to where it broke. It tells you how the program got there.",
		"A trail of breadcrumbs from the front door to the room where the vase fell.",
		`Traceback (most recent call last):
  File "app.py", line 12, in main
  File "app.py", line 5, in parse
ValueError: invalid literal for int()`,
		"Start at the line from your own code closest to the error, not at the library internals.",
		[]string{"Error message", "Call stack", "Debugging"}},
	{"Breakpoint", nil, "Tools & workflow", 1,
		"A marker telling a debugger to pause the program at a line, so you can inspect variables and step forward one line at a time.",
		"Pausing a film at the exact frame where something odd happens.",
		`breakpoint()      # Python: stop here in the debugger
(gdb) break main.c:42`,
		"A breakpoint shows real values; guessing shows what you hoped the values were.",
		[]string{"Debugging", "Stack trace"}},
	{"Log", []string{"logging", "log file", "print debugging"}, "Tools & workflow", 9,
		"Messages a program records about what it is doing, usually with a time and a level (debug, info, warning, error), to help diagnose problems later.",
		"A ship's log book: what happened, when, and how serious.",
		`logging.info("user %s logged in", user)
logging.error("payment failed: %s", err)`,
		"Never log passwords, tokens or personal data. Logs are copied, shipped and kept for a long time.",
		[]string{"Debugging", "Stack trace"}},
	{"Configuration", []string{"config", "config file", "settings"}, "Tools & workflow", 9,
		"Settings that change how a program behaves without changing its code: files (JSON, YAML, TOML), environment variables or command-line flags.",
		"The settings menu on a washing machine: same machine, different programme.",
		`./academy -registry my.json -no-color`,
		"Keep secrets (passwords, API keys) out of config files that go into Git.",
		[]string{"Environment variable", "Hardcode"}},
	{"Container", []string{"Docker", "image", "containerization"}, "Tools & workflow", 9,
		"A packaged program together with everything it needs to run (libraries, settings), isolated from other programs but sharing the host's operating system kernel. Docker is the best-known tool.",
		"A shipping container: the same box moves between ships, trains and trucks without unpacking.",
		`docker run -it python:3.13 python`,
		"Containers are not virtual machines: they share the host kernel, so they are lighter but less isolated.",
		[]string{"Virtual machine", "Deploy", "Kernel"}},
}

var vocabSystems = []Word{
	{"Operating system", []string{"OS"}, "Systems & concurrency", 6,
		"The software that manages the computer's hardware and lets programs share it safely: Linux, Windows, macOS, Android.",
		"The building manager who allocates rooms, keys, heating and lifts to all the tenants.",
		`Every open(), print() and malloc() eventually asks the OS for something.`,
		"The OS is more than the desktop you see; most of it is the kernel underneath.",
		[]string{"Kernel", "Process", "System call"}},
	{"Kernel", nil, "Systems & concurrency", 6,
		"The core of the operating system, running with full hardware privileges. It schedules processes, manages memory, and talks to devices.",
		"The engine room of a ship: passengers never go there, but nothing moves without it.",
		`uname -r        # shows your kernel's version`,
		"Linux is technically just a kernel; a full \"Linux\" system adds many other programs around it.",
		[]string{"Operating system", "System call", "Process"}},
	{"System call", []string{"syscall"}, "Systems & concurrency", 6,
		"A request from a program to the kernel for something only the kernel may do: open a file, read from the network, start a process.",
		"Filling in a form at the town hall's front desk: you cannot walk into the back office yourself.",
		`write(1, "hi\n", 3);    // C: the write system call to stdout
strace ./app             # watch a program's system calls`,
		"System calls are slow compared with normal function calls, which is why buffering exists.",
		[]string{"Kernel", "File descriptor", "Buffer"}},
	{"Process", []string{"processes", "PID"}, "Systems & concurrency", 6,
		"A running program, with its own memory and resources, managed by the operating system. Each has an ID (PID).",
		"A single tenant's flat in an apartment block: private rooms, shared building.",
		`ps aux          # list processes
kill 1234       # stop process 1234`,
		"A program is the file on disk; a process is one running instance of it. Running it twice gives two processes.",
		[]string{"Thread", "Operating system", "Exit code"}},
	{"Thread", []string{"threads", "multithreading", "goroutine"}, "Systems & concurrency", 6,
		"A path of execution inside a process. Threads in one process share its memory, so they can cooperate quickly, and can also trample each other. Go's goroutines are lightweight threads.",
		"Several cooks in one kitchen: they share the ingredients, and must not grab the same knife.",
		`t = threading.Thread(target=download, args=(url,))
t.start()
go download(url)     // Go: a goroutine`,
		"Shared memory plus threads needs synchronisation, or you get race conditions.",
		[]string{"Process", "Race condition", "Mutex", "Concurrency"}},
	{"Concurrency", []string{"parallelism", "concurrent", "parallel"}, "Systems & concurrency", 6,
		"Concurrency is dealing with many tasks in overlapping time (they take turns); parallelism is doing many at literally the same moment (on several CPU cores).",
		"Concurrency: one chef juggling three dishes. Parallelism: three chefs, one dish each.",
		`Waiting on 100 network requests at once: concurrency.
Crunching 8 image tiles on 8 cores: parallelism.`,
		"Concurrency is about structure; parallelism is about speed. You can have either without the other.",
		[]string{"Thread", "Async", "Race condition"}},
	{"Race condition", []string{"data race", "race"}, "Systems & concurrency", 6,
		"A bug where the result depends on the unlucky timing of threads or processes, typically two of them changing the same data at once.",
		"Two people booking the last seat at the same second, and both receiving a ticket.",
		`# two threads each run this 1,000 times:
count += 1      # read, add, write: steps can interleave
# final count is often less than 2,000`,
		"Race conditions may appear once in a million runs. Tools like go test -race or ThreadSanitizer find them.",
		[]string{"Mutex", "Thread", "Atomic operation"}},
	{"Mutex", []string{"lock", "locking", "mutual exclusion"}, "Systems & concurrency", 6,
		"A lock that lets only one thread at a time into a section of code, so shared data is changed safely.",
		"A single key to a one-person bathroom: whoever holds it goes in; everyone else waits.",
		`mu.Lock()
count++
mu.Unlock()`,
		"Forgetting to unlock, or locking two mutexes in different orders, leads to deadlock.",
		[]string{"Race condition", "Deadlock", "Thread"}},
	{"Deadlock", nil, "Systems & concurrency", 6,
		"When two or more threads wait on each other forever, each holding something the other needs, so none can continue.",
		"Two cars facing each other on a one-lane bridge, each waiting for the other to reverse.",
		`Thread A: lock(x) then lock(y)
Thread B: lock(y) then lock(x)    → both stuck`,
		"Always take locks in the same agreed order, and hold them as briefly as possible.",
		[]string{"Mutex", "Race condition"}},
	{"Atomic operation", []string{"atomic", "atomicity"}, "Systems & concurrency", 7,
		"An operation that happens completely or not at all, with no in-between state visible to anyone else.",
		"A bank transfer that either moves the money or doesn't; never \"taken from you but not arrived\".",
		`os.replace(tmp, path)   # atomic rename: readers see old or new, never half
atomic.AddInt64(&n, 1)   // Go: an atomic counter`,
		"This academy saves your registry atomically (temp file, fsync, rename) for exactly this reason.",
		[]string{"Transaction", "Race condition", "Mutex"}},
	{"Async", []string{"asynchronous", "await", "async/await", "non-blocking", "blocking", "promise", "future"}, "Systems & concurrency", 6,
		"Asynchronous code starts a slow task (like a download) and carries on with other work instead of blocking (waiting idle) until it finishes. async/await is syntax for writing such code in order.",
		"Ordering at a café with a buzzer: you sit down and chat, and come back when it buzzes.",
		`async def main():
    page = await fetch(url)    # other tasks run while waiting
    print(len(page))`,
		"Async helps with waiting (network, disk), not with heavy computation, which still needs real parallelism.",
		[]string{"Concurrency", "Callback", "Event loop"}},
	{"Event loop", []string{"event", "event-driven"}, "Systems & concurrency", 6,
		"A loop that waits for events (a key press, a network reply, a timer) and runs the code registered for each one. It powers browsers, GUIs and async servers.",
		"A receptionist who handles one visitor or phone call at a time, as they arrive, all day.",
		`while True:
    event = wait_for_next_event()
    handle(event)`,
		"If one handler takes long, everything else freezes. Keep handlers short.",
		[]string{"Async", "Callback"}},
	{"File descriptor", []string{"fd", "file handle"}, "Systems & concurrency", 6,
		"A small number the kernel gives a process to refer to an open file, socket or pipe. 0, 1 and 2 are stdin, stdout and stderr.",
		"A coat-check ticket: you hand in the number to get your coat back.",
		`int fd = open("data.txt", O_RDONLY);
read(fd, buf, sizeof buf);
close(fd);`,
		"Opening files without closing them leaks descriptors until the process hits \"too many open files\".",
		[]string{"System call", "Standard input and output", "Socket"}},
	{"Cache", []string{"caching", "cache hit", "cache miss", "CPU cache"}, "Systems & concurrency", 5,
		"A small, fast store that keeps copies of recently or frequently used data, so the next request is quicker. It exists at every level: CPU caches, browser caches, web caches.",
		"Keeping your most-used spices on the counter instead of in the cellar.",
		`@functools.cache
def fib(n): ...          # results are remembered`,
		"\"There are only two hard things in computer science: cache invalidation and naming things\" (Phil Karlton). Stale caches serve old data.",
		[]string{"Latency", "Memory", "Locality"}},
	{"Locality", []string{"locality of reference", "cache-friendly"}, "Systems & concurrency", 5,
		"Programs tend to reuse data they used recently (temporal locality) and data stored nearby (spatial locality). Caches depend on it.",
		"Books you just read are likely to be read again, and the one next to it on the shelf is likely next.",
		`// fast: walks memory in order
for (i...) for (j...) sum += a[i][j];
// slow: jumps across rows
for (j...) for (i...) sum += a[i][j];`,
		"Two programs with the same Big-O can differ 10× in speed because of locality.",
		[]string{"Cache", "Array", "Big-O notation"}},
	{"Latency", nil, "Systems & concurrency", 5,
		"How long one operation takes, from start to finish: the delay.",
		"How long a letter takes to arrive.",
		`L1 cache ≈ 1 ns, RAM ≈ 100 ns, SSD ≈ 100 µs, a transatlantic round trip ≈ 80 ms`,
		"Latency is not throughput: a lorry full of hard drives has huge throughput and terrible latency.",
		[]string{"Throughput", "Bandwidth", "Cache"}},
	{"Throughput", nil, "Systems & concurrency", 5,
		"How much work gets done per unit of time: requests per second, bytes per second.",
		"How many letters the post office delivers per day.",
		`A server handling 10,000 requests per second`,
		"Improving throughput (batching) can worsen latency (each item waits for its batch). You often trade one for the other.",
		[]string{"Latency", "Bandwidth"}},
	{"Bandwidth", nil, "Systems & concurrency", 8,
		"The maximum rate data can move through a connection or bus: its capacity.",
		"The width of a motorway: how many cars can pass per hour at most.",
		`A 100 Mbit/s link moves at most about 12.5 MB per second`,
		"Bandwidth is the limit; throughput is what you actually get.",
		[]string{"Throughput", "Latency"}},
	{"Stream", []string{"streaming", "byte stream"}, "Systems & concurrency", 6,
		"Data that arrives or leaves a piece at a time, in order, instead of all at once: a file being read, a network connection, keyboard input.",
		"Water from a tap, as opposed to a filled bucket handed to you.",
		`for line in open("big.log"):    # reads one line at a time
    if "ERROR" in line: print(line)`,
		"Streaming lets you handle files larger than your memory. Reading everything at once does not.",
		[]string{"Buffer", "Standard input and output", "Pipe"}},
	{"Stack overflow", []string{"stack overflow error", "RecursionError"}, "Systems & concurrency", 5,
		"A crash that happens when the call stack runs out of room, usually from recursion that goes too deep or never stops. (Also the name of the famous Q&A website.)",
		"Stacking trays until the pile hits the ceiling.",
		`def forever(n):
    return forever(n + 1)
forever(0)   # RecursionError: maximum recursion depth exceeded`,
		"Check the base case first. Very deep but correct recursion may need rewriting as a loop.",
		[]string{"Recursion", "Stack", "Call"}},
	{"Virtual memory", []string{"paging", "page", "swap"}, "Systems & concurrency", 6,
		"The OS gives each process its own private, pretend address space, and maps it onto real RAM in fixed-size pages, moving rarely used pages to disk (swap) if needed.",
		"Every hotel guest gets a key to \"room 1\", but reception quietly maps each guest's room 1 to a different real room.",
		`Two processes can both use address 0x1000 and never collide.`,
		"Heavy swapping (\"thrashing\") makes everything crawl. More RAM, not a faster CPU, is the fix.",
		[]string{"Memory", "Segmentation fault", "Process"}},
}

var vocabNetworks = []Word{
	{"Protocol", nil, "Networks & web", 8,
		"An agreed set of rules for how two parties communicate: message formats, order, and what to do when things go wrong. HTTP, TCP and DNS are protocols.",
		"The etiquette of a phone call: say hello, take turns, say goodbye.",
		`HTTP: client sends "GET /page", server replies "200 OK" and the page`,
		"Both sides must follow the same protocol version, or they talk past each other.",
		[]string{"HTTP", "TCP", "IP address"}},
	{"IP address", []string{"IP", "IPv4", "IPv6"}, "Networks & web", 8,
		"The numeric address of a device on a network, like 192.168.1.10 (IPv4) or 2001:db8::1 (IPv6), used to route data to it.",
		"A postal address for a computer.",
		`ping 1.1.1.1
127.0.0.1 is always "this machine" (localhost)`,
		"An IP address identifies a network interface, not a person, and it can change.",
		[]string{"Port", "DNS", "Protocol"}},
	{"Port", []string{"port number"}, "Networks & web", 8,
		"A number (0–65535) that picks which program on a machine should receive network traffic. Web servers usually listen on 443 (HTTPS) or 80 (HTTP).",
		"A flat number in an apartment building: the IP address is the building, the port is the flat.",
		`http://localhost:8080   # port 8080 on this machine`,
		"\"Address already in use\" means another program already listens on that port.",
		[]string{"IP address", "Socket", "Server"}},
	{"Socket", nil, "Networks & web", 8,
		"A program's endpoint for network communication: the operating system object you read from and write to when talking over the network.",
		"A telephone handset: pick it up, dial, then speak and listen.",
		`s = socket.create_connection(("example.com", 80))
s.sendall(b"GET / HTTP/1.0\r\n\r\n")`,
		"Networks deliver data in chunks; one send does not mean one receive on the other side.",
		[]string{"Port", "TCP", "File descriptor"}},
	{"Client and server", []string{"client", "server", "client-server", "backend", "frontend"}, "Networks & web", 8,
		"A server waits for requests and answers them; a client sends requests. Your browser is a client; a website runs on servers. \"Frontend\" is the part users see, \"backend\" the server side.",
		"A customer (client) ordering from a waiter, with the kitchen (server) cooking.",
		`python -m http.server 8000     # a tiny server
curl http://localhost:8000     # a client`,
		"\"Server\" can mean the program or the machine it runs on.",
		[]string{"HTTP", "Request and response", "API"}},
	{"TCP", []string{"UDP", "TCP/IP"}, "Networks & web", 8,
		"TCP is the protocol that gives programs a reliable, ordered stream of bytes over an unreliable network, resending lost pieces. UDP is the lighter alternative: fast, but with no delivery guarantee.",
		"TCP is a registered letter with tracking and redelivery; UDP is a postcard.",
		`Web pages, SSH and email use TCP; live video calls and games often use UDP.`,
		"TCP guarantees order and delivery, not speed. A lost packet delays everything behind it.",
		[]string{"Protocol", "Socket", "IP address"}},
	{"HTTP", []string{"HTTPS", "GET", "POST"}, "Networks & web", 8,
		"The protocol of the web: a client sends a request (a method like GET or POST, a path, headers, maybe a body) and the server sends back a response. HTTPS is HTTP inside TLS encryption.",
		"Ordering from a menu: \"GET me /soup\", and the kitchen replies \"200 OK, here is your soup\".",
		`GET /index.html HTTP/1.1
Host: example.com`,
		"HTTP itself is stateless: each request stands alone. Cookies and tokens carry state across requests.",
		[]string{"Request and response", "Status code", "TLS", "REST"}},
	{"Request and response", []string{"request", "response", "headers", "body"}, "Networks & web", 8,
		"The two halves of a client-server exchange: the client's request, and the server's response. Both have headers (metadata) and an optional body (the content).",
		"A letter you send, and the reply you get back, each with an envelope (headers) and a letter inside (body).",
		`resp = requests.get("https://example.com")
resp.status_code, resp.headers["Content-Type"], resp.text`,
		"Always check the response status before trusting the body.",
		[]string{"HTTP", "Status code", "API"}},
	{"Status code", []string{"HTTP status", "404", "500", "200"}, "Networks & web", 8,
		"A three-digit number in an HTTP response: 2xx success, 3xx redirect, 4xx the client's mistake (404 not found, 403 forbidden), 5xx the server's failure (500).",
		"A doctor's triage colour: green, redirected, your fault, their fault.",
		`200 OK · 301 Moved · 404 Not Found · 429 Too Many Requests · 503 Unavailable`,
		"A page can say \"Error\" with a 200 status. Programs should check the code, not the words.",
		[]string{"HTTP", "Request and response"}},
	{"TLS", []string{"SSL", "certificate", "HTTPS certificate"}, "Networks & web", 10,
		"The encryption layer that protects network connections (the S in HTTPS): it keeps data private, detects tampering, and proves the server's identity with a certificate.",
		"A sealed, tamper-evident envelope, delivered by a courier who shows official ID.",
		`curl -v https://example.com    # shows the TLS handshake and certificate`,
		"The padlock means the connection is encrypted, not that the site is honest.",
		[]string{"Encryption", "HTTP", "Public-key cryptography"}},
	{"DNS", []string{"domain name", "domain", "DNS lookup"}, "Networks & web", 8,
		"The internet's phone book: it translates names like example.com into IP addresses.",
		"Looking up a friend's name in your contacts to get their number.",
		`dig example.com
nslookup example.com`,
		"\"It's always DNS\" is a sysadmin joke with truth in it: many outages start with a broken DNS record.",
		[]string{"IP address", "Protocol"}},
	{"URL", []string{"URI", "link", "query string"}, "Networks & web", 8,
		"A web address: scheme, host, optional port, path, and optional query string, like https://example.com:443/search?q=cats.",
		"A full postal address down to the room number.",
		`https://api.example.com/v1/users?limit=10
scheme  host             path      query`,
		"Special characters in URLs must be encoded (space becomes %20). Never glue URLs together from raw user input.",
		[]string{"HTTP", "DNS", "Injection"}},
	{"JSON", []string{"JavaScript Object Notation"}, "Networks & web", 7,
		"A simple text format for structured data, using objects {\"key\": value}, arrays [ ], strings, numbers, true/false and null. The common language of web APIs, and the format of this academy's registry.",
		"A tidy form everyone agrees how to fill in, so any program can read it.",
		`{"name": "Ada", "langs": ["C", "Go"], "active": true}`,
		"JSON has no comments, no trailing commas, and keys must use double quotes.",
		[]string{"Serialization", "API", "Dictionary"}},
	{"REST", []string{"RESTful", "REST API"}, "Networks & web", 8,
		"A popular style for web APIs: resources have URLs, and standard HTTP methods act on them (GET to read, POST to create, PUT/PATCH to update, DELETE to delete).",
		"A library with shelf numbers for every book and a fixed set of desk actions: borrow, return, reserve.",
		`GET    /users/42      read user 42
DELETE /users/42      delete user 42`,
		"GET must never change data. Crawlers and browsers assume it is safe to repeat.",
		[]string{"API", "HTTP", "JSON"}},
	{"Cookie", []string{"session", "cookies"}, "Networks & web", 10,
		"A small piece of data a website asks the browser to store and send back with every request, often to remember that you are logged in (a session).",
		"A cloakroom ticket: show it each time so they know which coat is yours.",
		`Set-Cookie: session=abc123; HttpOnly; Secure; SameSite=Lax`,
		"A stolen session cookie is as good as a stolen password. That is why the HttpOnly and Secure flags matter.",
		[]string{"HTTP", "Authentication"}},
}

var vocabData = []Word{
	{"Database", []string{"DB", "DBMS", "RDBMS"}, "Data & databases", 7,
		"An organised, durable store of data with software (the database management system) to add, find, update and protect it, even with many users and crashes.",
		"A library with a catalogue and librarians, versus a pile of books on the floor.",
		`PostgreSQL, SQLite, MySQL (relational); Redis, MongoDB (non-relational)`,
		"A spreadsheet is not a database: no transactions, weak integrity, and it does not scale to many writers.",
		[]string{"SQL", "Transaction", "Database index", "Schema"}},
	{"SQL", []string{"query", "structured query language", "SELECT"}, "Data & databases", 7,
		"The standard language for relational databases: you describe what data you want, and the database works out how to get it.",
		"Asking a librarian \"all books by Knuth published after 1990\" instead of searching the shelves yourself.",
		`SELECT name, age FROM users
WHERE age >= 18
ORDER BY name;`,
		"SQL built by gluing strings together from user input is how SQL injection happens. Use parameters.",
		[]string{"Database", "SQL injection", "Database index"}},
	{"Schema", nil, "Data & databases", 7,
		"The declared shape of data: which tables or fields exist, their types, and the rules they must follow.",
		"The printed layout of a form: which boxes exist and what may go in each.",
		`CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT UNIQUE NOT NULL);`,
		"Changing a schema on live data needs a migration plan. This academy's registry has a schema_version for that reason.",
		[]string{"Database", "Primary key", "Migration"}},
	{"Primary key", []string{"foreign key", "key (database)", "ID"}, "Data & databases", 7,
		"A column that uniquely identifies each row in a table. A foreign key is a column that refers to another table's primary key, linking the two.",
		"A passport number (primary key); a ticket that lists a passport number links to that person (foreign key).",
		`orders.user_id REFERENCES users(id)`,
		"Do not use data that can change (like an email address) as a primary key.",
		[]string{"Schema", "Database"}},
	{"Database index", []string{"index (database)", "B-tree index"}, "Data & databases", 7,
		"An extra structure (usually a B-tree) a database keeps so it can find rows fast without scanning the whole table.",
		"The index at the back of a book.",
		`CREATE INDEX idx_users_email ON users(email);`,
		"Indexes speed up reads but slow down writes and take space. Add them for the queries you actually run.",
		[]string{"Database", "B-tree", "Big-O notation"}},
	{"Transaction", []string{"ACID", "rollback (database)"}, "Data & databases", 7,
		"A group of database changes that succeed or fail as one unit. ACID names its guarantees: Atomic, Consistent, Isolated, Durable.",
		"A bank transfer: debit and credit happen together or not at all.",
		`BEGIN;
UPDATE accounts SET balance = balance - 50 WHERE id = 1;
UPDATE accounts SET balance = balance + 50 WHERE id = 2;
COMMIT;`,
		"Without a transaction, a crash between the two updates makes money disappear.",
		[]string{"Atomic operation", "Database", "Commit"}},
	{"Serialization", []string{"serialize", "deserialize", "marshal", "unmarshal", "parse", "parsing"}, "Data & databases", 7,
		"Turning in-memory data into bytes or text (JSON, CSV, binary) to save or send it; deserializing (parsing) turns it back.",
		"Flat-packing furniture for shipping, and assembling it again at the other end.",
		`text = json.dumps({"a": 1})     # serialize
data = json.loads(text)         # deserialize (parse)`,
		"Never deserialize untrusted data with formats that can run code (Python's pickle).",
		[]string{"JSON", "Encoding", "Input validation"}},
	{"Migration", []string{"schema migration"}, "Data & databases", 7,
		"A controlled change to stored data or its schema, applied step by step so existing data keeps working.",
		"Moving house room by room while still living there.",
		`This academy migrates registries from schema 1 to 2 automatically.`,
		"Always back up before a migration, and test it on a copy of real data first.",
		[]string{"Schema", "Backup"}},
	{"Backup", []string{"backups", "snapshot"}, "Data & databases", 7,
		"A copy of data kept separately so it can be restored after mistakes, crashes or attacks.",
		"A spare house key kept at a friend's place.",
		`./academy -backups
./academy -restore 1`,
		"A backup you have never restored is only a hope. Test restores.",
		[]string{"Rollback", "Migration"}},
	{"CSV", []string{"comma-separated values"}, "Data & databases", 14,
		"A plain-text table format: one row per line, values separated by commas. Every spreadsheet can read and write it.",
		"A table written on lined paper with commas instead of column lines.",
		`name,age
Ada,36
"Hopper, Grace",85`,
		"Values containing commas or quotes must be quoted. Parse CSV with a real library, not split(\",\").",
		[]string{"Serialization", "JSON"}},
}
