package main

// Dictionary: basics, types & data, functions & structure.

var vocabBasics = []Word{
	{"Program", []string{"software", "code"}, "Basics", 1,
		"A list of precise instructions a computer follows, step by step. Software is one or more programs; \"code\" is the text they are written in.",
		"A recipe: exact steps, in order, that anyone (or anything) can follow without guessing.",
		`print("Hello")      # a complete one-line program in Python`,
		"A computer does exactly what the program says, not what you meant. Most bugs live in that gap.",
		[]string{"Source code", "Algorithm", "Bug"}},
	{"Source code", []string{"source"}, "Basics", 1,
		"The human-readable text of a program, as written by programmers, before it is turned into something the machine runs.",
		"Sheet music: people write and read it; an orchestra (the computer) turns it into sound.",
		`hello.c is source code; the file "hello" you get after compiling is not.`,
		"Source code is not what runs. A compiler or interpreter has to process it first.",
		[]string{"Compiler", "Interpreter", "Executable"}},
	{"Syntax", []string{"syntax error"}, "Basics", 1,
		"The grammar rules of a programming language: which symbols go where. A syntax error means the text breaks those rules, so the program cannot even start.",
		"Spelling and punctuation. \"Cat the sat mat on\" uses real words but broken grammar.",
		`print("hi"     # SyntaxError: '(' was never closed`,
		"Syntax is about form, not meaning. A program can have perfect syntax and still be completely wrong.",
		[]string{"Semantics", "Compiler", "Error message"}},
	{"Semantics", nil, "Basics", 11,
		"What a piece of code actually means and does when it runs, as opposed to how it is written (syntax).",
		"\"Colourless green ideas sleep furiously\" has perfect grammar but no sensible meaning.",
		`x = 10 / 4   # Python 3: semantics say this is 2.5
x = 10 / 4;  // C with ints: semantics say this is 2`,
		"The same-looking line can mean different things in different languages.",
		[]string{"Syntax", "Integer division"}},
	{"Statement", nil, "Basics", 1,
		"One complete instruction: \"do this\". A program is a sequence of statements.",
		"One sentence in a recipe: \"Preheat the oven.\"",
		`total = 0          # an assignment statement
if total > 10:     # an if statement
    print("big")`,
		"A statement does something; an expression produces a value. Some languages blur the line.",
		[]string{"Expression", "Block"}},
	{"Expression", nil, "Basics", 1,
		"A piece of code that produces a value, like 2 + 3, name.upper() or x > 5.",
		"A question with an answer: \"What is 2 + 3?\" gives 5.",
		`price * 1.2        # an expression; its value is the price plus 20%`,
		"If you can put it on the right of = or pass it to a function, it is an expression.",
		[]string{"Statement", "Operator", "Value"}},
	{"Variable", []string{"var"}, "Basics", 1,
		"A name that refers to a value stored in memory, so you can use and change the value later.",
		"A labelled box, or a name tag stuck on a thing. In Python it is closer to the tag; in C it is closer to the box.",
		`age = 30
age = age + 1      # the name now refers to 31`,
		"In maths, x = x + 1 is impossible. In code, = means \"make this name refer to\", not \"is equal to\".",
		[]string{"Assignment", "Constant", "Scope", "Memory address"}},
	{"Constant", []string{"const"}, "Basics", 1,
		"A named value that is not supposed to change while the program runs.",
		"The number of days in a week: you name it once and never change it.",
		`const double PI = 3.14159;   // C: the compiler refuses changes
MAX_USERS = 100               # Python: capitals say "please don't change"`,
		"Python has no real constants; ALL_CAPS is only a convention.",
		[]string{"Variable", "Magic number", "Immutable"}},
	{"Assignment", []string{"assign"}, "Basics", 1,
		"Giving a variable a value, usually with =.",
		"Writing a new label on a box's contents: \"this box now holds 5\".",
		`score = 0         # assignment
score == 0        # comparison: asks "is score 0?"`,
		"= assigns, == compares. Mixing them up in C (if (x = 0)) is a classic bug.",
		[]string{"Variable", "Operator"}},
	{"Value", nil, "Basics", 1,
		"A piece of data: a number, text, true/false, a list and so on. Variables refer to values.",
		"The contents of a box, as opposed to the label on it.",
		`42, "hello", True, [1, 2, 3] are all values`,
		"The variable and its value are different things: two names can refer to one value.",
		[]string{"Variable", "Data type", "Literal"}},
	{"Literal", nil, "Basics", 1,
		"A value written directly in the code, like 42, \"hi\" or True.",
		"A number printed in a recipe (\"200 g\") instead of \"the amount on the packet\".",
		`speed = 3.5       # 3.5 is a float literal
name = "Ada"      # "Ada" is a string literal`,
		"Too many unexplained literals scattered in code become \"magic numbers\".",
		[]string{"Value", "Magic number", "Constant"}},
	{"Keyword", []string{"reserved word"}, "Basics", 1,
		"A word the language reserves for itself, like if, for, while, return, class. You cannot use it as a variable name.",
		"Words on a form that are already printed: you cannot write your name over \"Signature\".",
		`class = 3        # SyntaxError in Python: class is a keyword`,
		"Built-in names (like len or print in Python) are not keywords, so you can accidentally overwrite them.",
		[]string{"Identifier", "Syntax"}},
	{"Identifier", []string{"name"}, "Basics", 1,
		"The name you give to a variable, function, class or anything else, following the language's naming rules.",
		"The name on a folder: it must be written in allowed characters so it can be found again.",
		`user_count, parseLine and MAX_SIZE are identifiers; 2fast is not`,
		"Good names are the cheapest documentation there is. Say what it is, not how it is stored.",
		[]string{"Variable", "Keyword", "Namespace"}},
	{"Comment", nil, "Basics", 1,
		"Text in the source code that the computer ignores, written for humans who read it.",
		"A sticky note on a recipe: \"use less salt, Grandma's tip\".",
		`# Python comment
// C and Go line comment
/* C block comment */`,
		"Comments should explain why, not repeat what the code already says.",
		[]string{"Documentation", "Source code"}},
	{"Operator", []string{"operand"}, "Basics", 1,
		"A symbol that performs an operation on values, called operands: + - * / % == < and or not, and so on.",
		"The buttons on a calculator; the numbers you type are the operands.",
		`7 % 3      # 1: the remainder ("modulo") operator
a and b    # logical operator`,
		"The same symbol can do different things by type: + adds numbers but joins strings.",
		[]string{"Expression", "Operator precedence", "Modulo"}},
	{"Operator precedence", []string{"precedence", "order of operations"}, "Basics", 1,
		"The rules for which operation happens first when several appear together, like multiplication before addition.",
		"The maths rule you learned at school (BODMAS or PEMDAS).",
		`2 + 3 * 4     # 14, not 20
(2 + 3) * 4   # 20: brackets make the order explicit`,
		"When in doubt, add brackets. Readers should not need to know the precedence table.",
		[]string{"Operator", "Expression"}},
	{"Modulo", []string{"mod", "remainder", "%"}, "Basics", 1,
		"The remainder after dividing one whole number by another, usually written %.",
		"Sharing 7 sweets between 3 children: each gets 2 and 1 is left over. 7 % 3 is 1.",
		`n % 2 == 0     # true when n is even
hour = (hour + 5) % 24   # wrap around a clock`,
		"For negative numbers, languages disagree: -7 % 3 is 2 in Python but -1 in C.",
		[]string{"Operator", "Integer division"}},
	{"Integer division", []string{"floor division", "//"}, "Basics", 1,
		"Division that throws away the fractional part and keeps a whole number.",
		"How many full boxes of 6 eggs can you fill with 20 eggs? 3, not 3.33.",
		`20 // 6        # Python: 3
20 / 6         # Python: 3.333...
20 / 6         // C with ints: 3`,
		"In C, Java and Go, dividing two integers is always integer division, a common source of surprise zeros.",
		[]string{"Modulo", "Integer", "Type casting"}},
	{"Boolean", []string{"bool", "true", "false"}, "Basics", 1,
		"A value that is either true or false. Named after the mathematician George Boole.",
		"A light switch: on or off, nothing in between.",
		`is_adult = age >= 18     # True or False
if is_adult and has_ticket: ...`,
		"Many languages treat 0, empty text and empty lists as false (\"falsy\"). That can hide bugs.",
		[]string{"Condition", "Truthy and falsy", "Logic gate"}},
	{"Truthy and falsy", []string{"truthy", "falsy"}, "Basics", 1,
		"Values that are not true or false themselves but act like them in a condition. In Python, 0, \"\", [] and None are falsy; almost everything else is truthy.",
		"An empty wallet counts as \"no money\" even though nobody said the word no.",
		`if items:          # runs only when the list is not empty
    print(items[0])`,
		"if count: skips the case count == 0 even when 0 is a valid answer. Write if count is not None: when you mean that.",
		[]string{"Boolean", "Null"}},
	{"Condition", []string{"if statement", "conditional"}, "Basics", 1,
		"A test that decides which code runs: if this is true, do that, else do something else.",
		"\"If it rains, take an umbrella; otherwise wear sunglasses.\"",
		`if temp > 30:
    print("hot")
elif temp > 15:
    print("mild")
else:
    print("cold")`,
		"Order matters: the first true branch wins and the rest are skipped.",
		[]string{"Boolean", "Loop", "Control flow"}},
	{"Control flow", nil, "Basics", 1,
		"The order in which a program's statements run, shaped by conditions, loops, function calls, returns and errors.",
		"The route through a choose-your-own-adventure book.",
		`for x in data:        # loop
    if x < 0: break   # jump out early
    total += x`,
		"When a program surprises you, trace its control flow step by step on paper.",
		[]string{"Condition", "Loop", "Exception"}},
	{"Loop", []string{"for loop", "while loop"}, "Basics", 1,
		"Code that repeats. A for loop repeats for each item or a set number of times; a while loop repeats while a condition stays true.",
		"Doing laps of a running track until you have done ten, or until you are tired.",
		`for name in names:        # once per item
    print(name)
while balance < goal:     # until the condition is false
    balance += save()`,
		"A while loop whose condition never becomes false is an infinite loop: the program hangs.",
		[]string{"Iteration", "Off-by-one error", "Condition"}},
	{"Iteration", []string{"iterate", "iterator", "iterable"}, "Basics", 1,
		"One pass through a loop; to iterate is to go through items one by one. An iterable is anything you can loop over; an iterator hands out items one at a time.",
		"Turning the pages of a book one by one. The book is the iterable; your bookmark is the iterator.",
		`for ch in "abc":   # iterating over a string: a, b, c
    print(ch)`,
		"Changing a list while iterating over it skips or repeats items. Loop over a copy instead.",
		[]string{"Loop", "Array"}},
	{"Block", []string{"code block"}, "Basics", 1,
		"A group of statements that belong together, like the body of an if or a loop. Python marks blocks with indentation; C, Java and Go use { }.",
		"A paragraph: sentences that belong to the same idea.",
		`if (ok) {          // C: braces make the block
    save();
    log("saved");
}`,
		"In C, if (ok) save(); log(); runs log() every time; only save() belongs to the if. Always use braces.",
		[]string{"Scope", "Indentation"}},
	{"Indentation", nil, "Basics", 1,
		"The spaces at the start of a line. In Python it defines which block a line belongs to; in most other languages it is only for readability.",
		"Indented items in a to-do list belong to the item above them.",
		`if ok:
    save()      # inside the if
print("done")   # outside the if`,
		"Mixing tabs and spaces breaks Python code in ways you cannot see. Configure your editor to insert spaces.",
		[]string{"Block", "Whitespace", "Formatter"}},
	{"Whitespace", nil, "Basics", 1,
		"Invisible characters: spaces, tabs and line breaks.",
		"The gaps between words: invisible, but reading without them is hard.",
		`"  hi \n".strip()    # "hi": removes surrounding whitespace`,
		"User input often carries hidden whitespace (\"yes \" is not \"yes\"). Trim it before comparing.",
		[]string{"Indentation", "Sanitization"}},
	{"Scope", nil, "Basics", 1,
		"The part of a program where a name exists and can be used. A variable made inside a function usually exists only inside it.",
		"A nickname used only at home: at work nobody knows who you mean.",
		`def f():
    secret = 1     # local to f
print(secret)      # NameError: not defined out here`,
		"A local variable with the same name as a global one hides (\"shadows\") the global. That causes confusing bugs.",
		[]string{"Variable", "Global variable", "Closure", "Namespace"}},
	{"Global variable", []string{"global"}, "Basics", 1,
		"A variable visible to the whole program, not just one function.",
		"The office whiteboard: anyone can read it, and anyone can scribble on it.",
		`count = 0          # global
def bump():
    global count     # Python needs this to change it
    count += 1`,
		"Globals make it hard to know who changed what. Prefer passing values as parameters.",
		[]string{"Scope", "Side effect"}},
	{"Bug", []string{"defect"}, "Basics", 1,
		"A mistake in a program that makes it behave wrongly. Grace Hopper's team famously taped a real moth that had jammed a relay into their 1947 log book as the \"first actual case of bug being found\".",
		"A typo in a recipe that says \"2 kg of salt\".",
		`total = price + tax * quantity   # bug: tax applied only once per item?`,
		"The program is not \"being weird\". It does exactly what you wrote. Find the difference between what you wrote and what you meant.",
		[]string{"Debugging", "Edge case", "Heisenbug"}},
	{"Debugging", []string{"debug", "debugger"}, "Basics", 1,
		"Finding and fixing bugs. A debugger is a tool that pauses a running program so you can inspect it line by line.",
		"Detective work: gather clues, form a theory, test it, repeat.",
		`python -m pdb app.py     # step through a Python program
gdb ./app                # step through a C program`,
		"Guessing and changing things at random is not debugging. Reproduce the bug first, then narrow it down.",
		[]string{"Bug", "Breakpoint", "Stack trace", "Rubber duck debugging"}},
	{"Error message", []string{"error"}, "Basics", 1,
		"The text a language prints when something goes wrong. It usually says what went wrong, and where.",
		"A car's dashboard warning light, with the page number of the manual.",
		`TypeError: can only concatenate str (not "int") to str
  File "app.py", line 3`,
		"Read error messages slowly, from the most specific line. Beginners often skip the one sentence that explains everything.",
		[]string{"Exception", "Stack trace", "Debugging"}},
	{"Compile time", []string{"compile-time"}, "Basics", 5,
		"When a program is being translated before it runs. Compile-time errors are caught before anyone uses the program.",
		"Spell-check before you send an email.",
		`int x = "hi";    // C: rejected at compile time`,
		"Errors found at compile time are cheap; the same errors at run time reach your users.",
		[]string{"Runtime", "Compiler", "Static typing"}},
	{"Runtime", []string{"run time", "run-time"}, "Basics", 5,
		"When a program is actually running. \"The runtime\" also names the support code that runs alongside a program (like Python's interpreter or Go's garbage collector).",
		"The live performance, as opposed to the rehearsal.",
		`items[10]    # IndexError at runtime if the list is shorter`,
		"A program that compiles can still crash at runtime. Compiling proves only that the code is well formed.",
		[]string{"Compile time", "Exception", "Garbage collection"}},
	{"Exception", []string{"throw", "raise", "try/except", "try/catch"}, "Basics", 1,
		"A signal that something went wrong at runtime. It stops normal flow and jumps to the nearest code that handles (\"catches\") it, or crashes the program with an error message.",
		"A fire alarm: everyone stops what they are doing and follows the emergency plan.",
		`try:
    n = int(text)
except ValueError:
    print("not a number")`,
		"Catching every exception and ignoring it (except: pass) hides bugs. Catch only what you can actually handle.",
		[]string{"Error message", "Control flow", "Stack trace"}},
}

var vocabTypes = []Word{
	{"Logic gate", []string{"AND gate", "OR gate", "NOT gate", "NAND"}, "Types & data", 4,
		"A tiny circuit that takes one or two bits in and gives one bit out by a fixed rule: AND (both 1), OR (either 1), NOT (flip). Every CPU is billions of them.",
		"Two light switches wired in series (AND: both must be on) or in parallel (OR: either will do).",
		`a and b     # Python's boolean AND is the same rule as an AND gate
a & b       // C bitwise AND works on every bit at once`,
		"and/or (logical, on true/false) and &/| (bitwise, on each bit) are different operators.",
		[]string{"Boolean", "Bit", "Binary"}},
	{"Data type", []string{"type"}, "Types & data", 1,
		"The kind of a value, which decides what you can do with it: integer, floating-point number, string, boolean, list and so on.",
		"Liquids go in bottles, eggs go in cartons: the container depends on the kind of thing.",
		`type(3)       # int
type("3")     # str: looks the same, but a different type`,
		"\"3\" and 3 are different: one is text, one is a number. Many beginner bugs are type mix-ups.",
		[]string{"Type casting", "Static typing", "Dynamic typing"}},
	{"Integer", []string{"int"}, "Types & data", 1,
		"A whole number with no fractional part: -2, 0, 42. In C and most languages it has a fixed size (often 32 or 64 bits), so it has a maximum value.",
		"Counting people: you can have 3 people, never 3.5.",
		`int count = 2147483647;   // C: largest 32-bit int
count + 1                 // overflow: undefined behaviour in C`,
		"Python integers grow as large as needed; C, Java and Go integers do not, and they overflow.",
		[]string{"Integer overflow", "Floating point", "Bit"}},
	{"Floating point", []string{"float", "double", "floating-point number"}, "Types & data", 4,
		"The usual way computers store numbers with fractions, like 3.14. It is binary scientific notation, so most decimals are stored only approximately.",
		"Measuring with a ruler that has only so many marks: close, but rarely exact.",
		`0.1 + 0.2 == 0.3        # False
abs((0.1 + 0.2) - 0.3) < 1e-9   # True: compare with a tolerance`,
		"Never store money in floats. Use whole cents (integers) or a decimal type.",
		[]string{"Integer", "Precision", "Type casting"}},
	{"Precision", []string{"rounding error"}, "Types & data", 4,
		"How many significant digits a number type can hold. Beyond that, values are rounded, and small errors can pile up.",
		"A kitchen scale that shows grams: it cannot tell 10.2 g from 10.4 g.",
		`sum([0.1] * 10)     # 0.9999999999999999, not 1.0`,
		"Rounding for display is fine; rounding in the middle of a calculation can change the answer.",
		[]string{"Floating point", "Truncation"}},
	{"String", []string{"str", "text"}, "Types & data", 1,
		"A sequence of characters: text. Usually written in quotes.",
		"Beads on a thread, each bead a character.",
		`name = "Ada"
name[0]          # "A"
name + "!"       # "Ada!"`,
		"Strings are often immutable: name.upper() returns a new string and leaves name unchanged.",
		[]string{"Character", "Encoding", "Immutable"}},
	{"Character", []string{"char"}, "Types & data", 1,
		"One symbol of text: a letter, digit, space or emoji. In C, a char is one byte, which is not the same as one visible character.",
		"One tile in a game of Scrabble.",
		`char c = 'A';        // C: single quotes for one char
printf("%d", c);     // 65: it is stored as a number`,
		"An emoji or an accented letter can take several bytes. Length in bytes is not length in characters.",
		[]string{"String", "Encoding", "Byte"}},
	{"Encoding", []string{"UTF-8", "Unicode", "ASCII", "character encoding"}, "Types & data", 1,
		"The rule for turning characters into bytes and back. ASCII covers basic English; Unicode numbers every character in every script; UTF-8 is the common way to store Unicode as bytes.",
		"Morse code: an agreed mapping between letters and signals. Decode with the wrong table and you get nonsense.",
		`"é".encode("utf-8")    # b'\xc3\xa9': 2 bytes for 1 character`,
		"Garbled text like \"cafÃ©\" means bytes were decoded with the wrong encoding. Use UTF-8 everywhere.",
		[]string{"Character", "Byte", "String"}},
	{"Bit", []string{"binary digit"}, "Types & data", 4,
		"The smallest unit of information: a single 0 or 1.",
		"A single light switch: on or off.",
		`0b1011     # the number 11 written in binary bits`,
		"b (bits) and B (bytes) differ by 8×. Internet speeds are usually in bits per second.",
		[]string{"Byte", "Binary", "Integer"}},
	{"Byte", nil, "Types & data", 4,
		"A group of 8 bits, able to hold 256 different values (0–255). Memory and files are measured in bytes.",
		"A row of eight light switches: 256 possible patterns.",
		`1 KB ≈ 1,000 bytes (KiB = 1,024), 1 MB ≈ a million bytes`,
		"KB can mean 1,000 or 1,024 bytes depending on who writes it; KiB always means 1,024.",
		[]string{"Bit", "Memory address", "Encoding"}},
	{"Binary", []string{"base 2"}, "Types & data", 4,
		"Counting with only two digits, 0 and 1. Computers use it because circuits reliably tell two voltage levels apart. \"A binary\" also means a compiled program file.",
		"Counting on fingers that can only be up or down.",
		`bin(6)     # '0b110': 4 + 2 + 0`,
		"\"Binary\" the number system and \"a binary\" (an executable file) are different meanings.",
		[]string{"Bit", "Hexadecimal", "Executable"}},
	{"Hexadecimal", []string{"hex", "base 16", "0x"}, "Types & data", 4,
		"Counting in base 16, with digits 0–9 and A–F. Programmers use it as a compact way to write bytes: two hex digits are exactly one byte.",
		"A shorthand: writing 1111 1111 as FF is like writing a dozen instead of twelve ones.",
		`0xFF        # 255
#FF8800     # a colour: red FF, green 88, blue 00`,
		"0x10 is sixteen, not ten.",
		[]string{"Binary", "Byte", "Memory address"}},
	{"Type casting", []string{"type conversion", "cast", "casting", "convert", "coercion", "type coercion"}, "Types & data", 1,
		"Turning a value of one type into another type: text into a number, a float into an int, and so on. Explicit casting is when you ask for it; implicit conversion (coercion) is when the language does it for you automatically.",
		"Changing currency: 10 euros becomes some number of dollars. The amount is \"the same\", but its form changes, and a little can be lost in the exchange.",
		`int("42")      # 42: string to integer (explicit)
str(42)        # "42": integer to string
int(3.99)      # 3: float to int drops the fraction
(int)3.99      // C cast: also 3
3 + 2.5        # 5.5: the int is converted to float implicitly
"3" + 3        # Python: TypeError, it refuses to guess
"3" + 3        // JavaScript: "33", it guesses (coercion)`,
		"Casting a float to int truncates, it does not round: int(2.9) is 2. And int(\"4.5\") fails; convert to float first.",
		[]string{"Data type", "Implicit conversion", "Truncation", "Static typing"}},
	{"Implicit conversion", []string{"implicit cast", "automatic conversion"}, "Types & data", 1,
		"A type conversion the language performs on its own, without you writing a cast, usually when mixing types in one expression.",
		"A shop that accepts foreign coins and silently converts them at its own rate.",
		`double avg = sum / count;   // C: if both are ints, the division
                            // happens first as integers, THEN converts`,
		"Implicit conversions happen at surprising moments. When the types matter, cast explicitly.",
		[]string{"Type casting", "Integer division", "Weak typing"}},
	{"Truncation", []string{"truncate"}, "Types & data", 1,
		"Cutting off part of a value: the fraction of a number, or the end of a string or file.",
		"Cutting a long ribbon to fit a box: the extra is simply gone.",
		`int(-2.7)    # -2: truncation goes towards zero
round(2.7)   # 3: rounding is different`,
		"Truncation and rounding are different. Decide which one you mean.",
		[]string{"Type casting", "Precision"}},
	{"Static typing", []string{"statically typed"}, "Types & data", 11,
		"The type of every variable is known and checked before the program runs (at compile time). C, Go, Java and Rust are statically typed.",
		"A form with labelled boxes: \"Age (number)\". A clerk rejects it before processing if you wrote text there.",
		`int n = 5;
n = "five";      // C: compile error`,
		"Static typing catches mistakes early, but it does not prove the program is correct.",
		[]string{"Dynamic typing", "Type inference", "Compile time"}},
	{"Dynamic typing", []string{"dynamically typed", "duck typing"}, "Types & data", 11,
		"Types belong to values, not variables, and are checked only while the program runs. Python, JavaScript and Ruby are dynamically typed.",
		"A box with no label: you find out what is inside when you open it.",
		`x = 5
x = "five"       # fine in Python: x now refers to a string`,
		"Dynamic typing is flexible, but type mistakes appear at runtime, possibly in front of users. Type hints and tests help.",
		[]string{"Static typing", "Runtime"}},
	{"Strong and weak typing", []string{"strong typing", "weak typing", "weakly typed", "strongly typed"}, "Types & data", 11,
		"Informal terms for how willing a language is to convert types automatically. \"Weak\" languages convert freely (JavaScript: \"3\" * 2 is 6); \"strong\" ones refuse (Python: TypeError).",
		"A strict bank that refuses foreign coins, versus a relaxed one that converts anything at whatever rate.",
		`"3" * 2     # Python: "33" (repeat the string), not 6!`,
		"People use these words loosely. Say exactly what you mean: \"converts implicitly\" or \"checks at compile time\".",
		[]string{"Implicit conversion", "Static typing", "Dynamic typing"}},
	{"Type inference", nil, "Types & data", 11,
		"The compiler works out a variable's type from its value, so you do not have to write it, while still checking types statically.",
		"A waiter who sees you holding a coffee cup and assumes you want a refill.",
		`x := 42          // Go: x is inferred to be an int
let s = "hi";    // Rust: s is a &str`,
		"Inferred does not mean dynamic: the type is still fixed once chosen.",
		[]string{"Static typing", "Data type"}},
	{"Null", []string{"None", "nil", "NULL", "null value"}, "Types & data", 1,
		"A special value meaning \"nothing here\" or \"no value\". Called None in Python, nil in Go, NULL in C and SQL.",
		"An empty parking space: the space exists, but there is no car in it.",
		`user = find_user("bob")   # may return None
if user is not None:
    print(user.name)`,
		"Using a null as if it were a real value crashes programs. Its inventor, Tony Hoare, called it his \"billion-dollar mistake\".",
		[]string{"Null pointer", "Truthy and falsy"}},
	{"Array", []string{"arrays"}, "Types & data", 2,
		"A fixed-size row of items of the same type, stored side by side in memory and accessed by a number (the index), usually starting at 0.",
		"A row of numbered lockers: you go straight to locker 7.",
		`int scores[5] = {90, 72, 85, 60, 99};  // C
scores[0]    // 90: indexes start at 0`,
		"The last valid index is length - 1. Going past the end in C reads random memory instead of raising an error.",
		[]string{"List", "Index", "Buffer overflow", "Off-by-one error"}},
	{"Index", []string{"indexes", "indices", "zero-based"}, "Types & data", 2,
		"The position number of an item in a sequence. Most languages count from 0. (A database index is something else: see Database index.)",
		"Floor numbers in many countries: the ground floor is 0, the next is 1.",
		`letters = ["a", "b", "c"]
letters[0]     # "a"
letters[-1]    # "c": Python counts backwards from -1`,
		"Starting at 0 means the index of the nth item is n - 1.",
		[]string{"Array", "Off-by-one error"}},
	{"List", []string{"dynamic array", "slice"}, "Types & data", 2,
		"An ordered collection that can grow and shrink. Python's list, C++'s vector and Go's slice are dynamic arrays under the hood.",
		"A shopping list: add items, cross some out, keep the order.",
		`todo = ["milk"]
todo.append("eggs")      # ["milk", "eggs"]`,
		"Inserting at the front of a dynamic array moves every other item. Adding at the end is cheap.",
		[]string{"Array", "Linked list", "Big-O notation"}},
	{"Dictionary", []string{"dict", "hash map", "hash table", "map", "associative array", "object (JSON)"}, "Types & data", 2,
		"A collection of key → value pairs, so you look values up by name instead of position. Usually built as a hash table, which makes lookups very fast.",
		"A real dictionary, or a phone's contacts: look up \"Mum\" and get her number.",
		`ages = {"ada": 36, "alan": 41}
ages["ada"]       # 36`,
		"Keys must be unique; assigning an existing key overwrites the old value.",
		[]string{"Hash function", "Set", "JSON"}},
	{"Set", nil, "Types & data", 2,
		"An unordered collection with no duplicates, built for fast \"is this in it?\" checks.",
		"A guest list: each name appears once, and the order does not matter.",
		`seen = {"a", "b"}
"a" in seen        # True, fast even for millions of items`,
		"Sets forget order and duplicates. Do not use one when either matters.",
		[]string{"Dictionary", "Hash function"}},
	{"Tuple", nil, "Types & data", 1,
		"A small, fixed, ordered group of values, often of different types. In Python, tuples cannot be changed.",
		"A postal address: street, city, postcode, always together and in that order.",
		`point = (3, 4)
x, y = point        # "unpacking"`,
		"(5) is just the number 5; a one-item tuple needs a comma: (5,).",
		[]string{"List", "Immutable", "Struct"}},
	{"Struct", []string{"record", "structure"}, "Types & data", 5,
		"A custom type that groups named fields together. Classes build on the same idea.",
		"A form with named fields: name, age, email.",
		`struct Point { int x; int y; };   // C
struct Point p = {3, 4};
p.x    // 3`,
		"Copying a struct in C copies all its fields; copying a pointer to it does not.",
		[]string{"Class", "Object", "Tuple"}},
	{"Enum", []string{"enumeration"}, "Types & data", 11,
		"A type with a fixed, named set of possible values, like the days of the week.",
		"A traffic light: red, amber or green, nothing else.",
		`enum Color { RED, GREEN, BLUE };   // C: RED is 0, GREEN 1…`,
		"Using plain strings (\"red\", \"Red\", \"RED\") instead of an enum invites typos that nothing catches.",
		[]string{"Constant", "Data type"}},
	{"Mutable", []string{"immutable", "mutability", "immutability"}, "Types & data", 12,
		"A mutable value can be changed in place; an immutable one cannot, so any \"change\" makes a new value. In Python, lists are mutable, strings and tuples immutable.",
		"A whiteboard (mutable) versus a printed page (immutable): to change the page you print a new one.",
		`a = [1, 2]
b = a
b.append(3)
print(a)     # [1, 2, 3]: a and b are the SAME list`,
		"Two names for one mutable object means a change through one name shows up through the other. This surprises everyone once.",
		[]string{"Reference", "Side effect", "Value"}},
	{"Integer overflow", []string{"overflow", "wraparound"}, "Types & data", 4,
		"When a calculation's result is too big (or too small) for its fixed-size integer type. It may wrap around to a small or negative number, or, for signed ints in C, be undefined behaviour.",
		"A car's odometer rolling from 999999 back to 000000.",
		`unsigned char b = 255;
b = b + 1;      // wraps to 0
int big = INT_MAX; big + 1;   // undefined behaviour in C`,
		"Overflow has caused real disasters, including the Ariane 5 rocket explosion in 1996. Check ranges in safety-critical code.",
		[]string{"Integer", "Undefined behavior", "Bit"}},
}

var vocabFunctions = []Word{
	{"Function", []string{"subroutine", "procedure", "routine"}, "Functions & structure", 1,
		"A named, reusable block of code that takes inputs, does a job, and can give back a result.",
		"A kitchen blender: put ingredients in, press the button, get a smoothie out, without redoing the wiring each time.",
		`def area(width, height):
    return width * height

area(3, 4)     # 12`,
		"Defining a function does not run it; calling it does.",
		[]string{"Parameter", "Argument", "Return value", "Call"}},
	{"Parameter", nil, "Functions & structure", 1,
		"A named input in a function's definition: the placeholder.",
		"The blank on a form: \"Name: ____\".",
		`def greet(name):    # name is a parameter
    print("Hi", name)`,
		"Parameter is the placeholder in the definition; argument is the actual value you pass in.",
		[]string{"Argument", "Function"}},
	{"Argument", []string{"arg", "args"}, "Functions & structure", 1,
		"The actual value you pass to a function when you call it. (Command-line arguments are the words typed after a program's name.)",
		"What you write in the blank: \"Name: Ada\".",
		`greet("Ada")      # "Ada" is the argument
./academy -registry my.json   # command-line arguments`,
		"Mnemonic: Parameters are Placeholders; Arguments are Actual values.",
		[]string{"Parameter", "Function", "Call"}},
	{"Return value", []string{"return"}, "Functions & structure", 1,
		"The result a function hands back to whoever called it. return also ends the function immediately.",
		"The receipt the cashier hands back after you pay.",
		`def double(n):
    return n * 2
x = double(5)     # x is 10`,
		"Printing is not returning. print shows a value to a human; return gives it to the code.",
		[]string{"Function", "Side effect"}},
	{"Call", []string{"invoke", "function call", "call site"}, "Functions & structure", 1,
		"Running a function: its name followed by brackets containing the arguments.",
		"Pressing the blender's button.",
		`len("hello")       # calling len
len                # just the function itself, NOT a call`,
		"Forgetting the () passes the function around instead of calling it.",
		[]string{"Function", "Call stack"}},
	{"Side effect", []string{"side effects"}, "Functions & structure", 12,
		"Anything a function does besides returning a value: printing, writing a file, changing a global variable or modifying its arguments.",
		"A coffee machine that also rings a bell in the next room: useful sometimes, confusing if you did not expect it.",
		`def add_item(cart, item):
    cart.append(item)     # side effect: changes the caller's list`,
		"Hidden side effects make code hard to reason about and test.",
		[]string{"Pure function", "Global variable", "Mutable"}},
	{"Pure function", []string{"pure"}, "Functions & structure", 12,
		"A function whose result depends only on its inputs and that has no side effects. Same inputs, same output, every time.",
		"A calculator: 2 + 2 is always 4, and pressing the keys changes nothing else in the world.",
		`def square(x):
    return x * x        # pure
def now_plus(x):
    return time.time() + x   # not pure: depends on the clock`,
		"Pure functions are the easiest code to test, cache and run in parallel.",
		[]string{"Side effect", "Functional programming"}},
	{"Recursion", []string{"recursive", "base case"}, "Functions & structure", 2,
		"A function that solves a problem by calling itself on a smaller version of the same problem, until it reaches a base case simple enough to answer directly.",
		"Russian nesting dolls: open one to find a smaller one, until the smallest doll that does not open.",
		`def factorial(n):
    if n <= 1:           # base case
        return 1
    return n * factorial(n - 1)`,
		"Without a base case (or with one never reached), recursion never stops and ends in a stack overflow.",
		[]string{"Call stack", "Stack overflow", "Function"}},
	{"Callback", []string{"callback function"}, "Functions & structure", 12,
		"A function you pass to other code so that code can call it later, for example when an event happens or a task finishes.",
		"Leaving your number with a shop: \"call me back when it's in stock\".",
		`button.on_click(save)         # save is a callback
sorted(words, key=len)        # len is called back for each word`,
		"Pass the function (save), not the result of calling it (save()).",
		[]string{"Higher-order function", "Async", "Event"}},
	{"Higher-order function", nil, "Functions & structure", 12,
		"A function that takes another function as an argument, or returns one. map, filter and sorted(key=...) are examples.",
		"A machine that takes a tool as input: a drill that accepts different bits.",
		`list(map(str.upper, ["a", "b"]))    # ["A", "B"]`,
		"These are ordinary functions; the only twist is that functions are values you can pass around.",
		[]string{"Callback", "Lambda", "Closure"}},
	{"Lambda", []string{"anonymous function", "arrow function"}, "Functions & structure", 12,
		"A small function without a name, written inline, usually to pass to another function. The name comes from Alonzo Church's lambda calculus.",
		"A sticky-note instruction you hand over once, instead of writing a whole manual.",
		`sorted(people, key=lambda p: p.age)
// JavaScript: people.map(p => p.name)`,
		"If a lambda grows beyond one simple expression, give it a proper name with def.",
		[]string{"Higher-order function", "Closure"}},
	{"Closure", nil, "Functions & structure", 12,
		"A function that remembers variables from the place where it was created, even after that place has finished running.",
		"A backpack a function carries: it packed some variables when it was made and keeps them.",
		`def counter():
    n = 0
    def bump():
        nonlocal n
        n += 1
        return n
    return bump
c = counter(); c(); c()    # 2`,
		"Closures created in a loop may all share the loop variable's final value. Bind it explicitly.",
		[]string{"Scope", "Lambda", "Higher-order function"}},
	{"Method", nil, "Functions & structure", 12,
		"A function that belongs to an object or class, and is called with a dot: object.method().",
		"A verb attached to a noun: dog.bark(), door.open().",
		`"hello".upper()     # upper is a method of strings
cart.add(item)`,
		"In Python, the first parameter of a method (self) is the object itself, passed automatically.",
		[]string{"Class", "Object", "Function"}},
	{"Class", nil, "Functions & structure", 12,
		"A blueprint describing a kind of object: what data it holds (attributes) and what it can do (methods).",
		"An architect's blueprint for a house. The blueprint is not a house, but you can build many houses from it.",
		`class Dog:
    def __init__(self, name):
        self.name = name
    def bark(self):
        return self.name + " says woof"`,
		"The class is the blueprint; objects (instances) are the actual things built from it.",
		[]string{"Object", "Instance", "Constructor", "Inheritance"}},
	{"Object", []string{"instance"}, "Functions & structure", 12,
		"A concrete thing built from a class, with its own data. \"Instance\" means the same: rex is an instance of Dog. (In everyday code, \"object\" can also mean any value.)",
		"An actual house built from the blueprint, with its own paint colour and furniture.",
		`rex = Dog("Rex")      # rex is an object (an instance of Dog)
rex.bark()`,
		"Two objects from the same class have separate data: changing rex.name does not change fido.name.",
		[]string{"Class", "Method", "Constructor"}},
	{"Constructor", []string{"__init__", "initializer"}, "Functions & structure", 12,
		"The special method that sets up a new object when it is created.",
		"Move-in day: the furniture is placed and the utilities switched on.",
		`class Account:
    def __init__(self, owner):
        self.owner = owner
        self.balance = 0`,
		"The constructor runs once per object, at creation time.",
		[]string{"Class", "Object"}},
	{"Inheritance", []string{"subclass", "superclass", "parent class", "child class"}, "Functions & structure", 12,
		"Making a new class that reuses and extends an existing one. The new class (subclass) gets the parent's attributes and methods and can add or change some.",
		"A new car model based on last year's: same chassis, a few changes.",
		`class Puppy(Dog):
    def bark(self):
        return "yip!"`,
		"Deep inheritance trees get brittle. Often \"has a\" (composition) is better than \"is a\" (inheritance).",
		[]string{"Class", "Polymorphism", "Composition"}},
	{"Composition", nil, "Functions & structure", 12,
		"Building complex things by combining simpler objects that each do one job, instead of inheriting from them.",
		"A car has an engine, wheels and seats; it is not a kind of engine.",
		`class Car:
    def __init__(self):
        self.engine = Engine()    # has-an engine`,
		"\"Favour composition over inheritance\" is common advice from the Design Patterns book.",
		[]string{"Inheritance", "Abstraction"}},
	{"Interface", []string{"trait"}, "Functions & structure", 12,
		"A list of methods a type promises to provide, without saying how. Any type that provides them can be used in the same place.",
		"A wall socket: any plug of the right shape works, whatever the appliance.",
		`type Writer interface {     // Go
    Write(p []byte) (int, error)
}`,
		"\"Interface\" also means, more loosely, how any piece of code is meant to be used, as in API.",
		[]string{"Polymorphism", "API", "Abstraction"}},
	{"Polymorphism", nil, "Functions & structure", 12,
		"One piece of code working with values of many different types, because they share an interface. The name means \"many shapes\".",
		"A universal remote: the same \"play\" button works on the TV, the speaker and the projector.",
		`for shape in [Circle(1), Square(2)]:
    print(shape.area())     # each computes area its own way`,
		"It sounds exotic, but you use it every time len() works on both strings and lists.",
		[]string{"Interface", "Inheritance"}},
	{"Encapsulation", nil, "Functions & structure", 9,
		"Keeping an object's internal data private and exposing only safe operations, so the rest of the program cannot put it into an invalid state.",
		"A cash machine: you can withdraw through the interface, but you cannot reach into the vault.",
		`class Account:
    def withdraw(self, amount):
        if amount > self._balance:     # rule enforced in one place
            raise ValueError("insufficient funds")
        self._balance -= amount`,
		"Python's leading underscore (_balance) is only a convention; the language does not enforce privacy.",
		[]string{"Abstraction", "Class", "Interface"}},
	{"Abstraction", []string{"abstract"}, "Functions & structure", 9,
		"Hiding details behind a simpler idea, so you can use something without knowing how it works inside.",
		"Driving a car with a steering wheel and pedals, without thinking about fuel injection.",
		`open("notes.txt").read()   # hides disks, sectors, caches, drivers`,
		"Abstractions \"leak\": when something breaks underneath, you need to know the layer below. That is why this academy teaches the layers.",
		[]string{"Encapsulation", "Interface", "API"}},
	{"Module", []string{"import"}, "Functions & structure", 9,
		"A file (or group of files) of code that you can import and use from other code.",
		"A chapter in a book that other chapters can refer to.",
		`import math
math.sqrt(16)      # 4.0`,
		"Naming your own file random.py or math.py hides the standard module of the same name.",
		[]string{"Package", "Library", "Namespace"}},
	{"Package", []string{"package manager", "pip", "npm"}, "Functions & structure", 9,
		"A bundle of modules distributed together. A package manager (pip, npm, cargo, apt) downloads and installs packages and their dependencies.",
		"A flat-pack furniture box: all the parts for one thing, plus instructions; the package manager is the delivery service.",
		`pip install requests
go get example.com/pkg`,
		"Installing a package runs other people's code on your machine. Check what you install.",
		[]string{"Library", "Dependency", "Module"}},
	{"Library", []string{"lib", "standard library", "stdlib"}, "Functions & structure", 9,
		"Reusable code written by others that your program calls. The standard library is the one that ships with the language.",
		"A toolbox: you pick the tool you need and use it.",
		`import json         # Python standard library
#include <stdio.h>   // C standard library`,
		"You call a library; a framework calls you. That is the usual distinction.",
		[]string{"Framework", "Package", "API", "Dependency"}},
	{"Framework", nil, "Functions & structure", 9,
		"A larger structure that controls the overall flow of your program and calls your code at the right moments (Django, React, Spring).",
		"A house's frame: you add rooms and furniture, but the frame decides the shape.",
		`@app.route("/hello")     # Flask calls this when /hello is requested
def hello():
    return "Hi"`,
		"Frameworks come and go; the fundamentals underneath them (HTTP, SQL, data structures) stay.",
		[]string{"Library", "API"}},
	{"API", []string{"application programming interface", "endpoint", "web API"}, "Functions & structure", 9,
		"The set of functions, commands or web addresses a piece of software offers so other programs can use it, and the rules for calling them.",
		"A restaurant menu: it lists what you can order and how, without showing you the kitchen.",
		`GET https://api.example.com/users/42   # a web API endpoint
len(x), open(path)                      # Python's built-in API`,
		"An API is a promise. Changing it breaks everyone who depends on it, which is why versions and deprecation exist.",
		[]string{"Interface", "Library", "REST", "HTTP"}},
	{"Dependency", []string{"dependencies", "deps"}, "Functions & structure", 9,
		"Code your project relies on but did not write: libraries, packages and tools.",
		"The ingredients you buy for a recipe: if the shop changes one, your dish changes too.",
		`requirements.txt, package.json and go.mod list dependencies`,
		"Every dependency is code you must trust and keep updated. This academy's app has zero on purpose.",
		[]string{"Package", "Library", "Supply-chain attack"}},
	{"Namespace", nil, "Functions & structure", 9,
		"A container that keeps names apart, so two things with the same name do not clash.",
		"Surnames: two people called Sam are told apart as Sam Smith and Sam Jones.",
		`math.log(x)       # log from the math module
logging.log(...)  # a different log, in another namespace`,
		"from module import * dumps every name into yours and invites clashes.",
		[]string{"Module", "Scope", "Identifier"}},
	{"Functional programming", []string{"FP"}, "Functions & structure", 12,
		"A style of programming built from pure functions and immutable data, combining small functions instead of changing state step by step.",
		"An assembly line of stations that each take something in and hand something new on, never altering what they received.",
		`total = sum(x * x for x in nums if x > 0)`,
		"It is a style you can use in most languages, not only in \"functional languages\" like Haskell.",
		[]string{"Pure function", "Higher-order function", "Immutable"}},
	{"Object-oriented programming", []string{"OOP", "object oriented"}, "Functions & structure", 12,
		"A style of programming that models a program as objects which bundle data with the methods that act on it.",
		"A company of employees, each responsible for their own files and tasks, who send each other requests.",
		`account.deposit(50)     # ask the object to act on its own data`,
		"OOP is a tool, not a religion. Not every problem needs a class.",
		[]string{"Class", "Object", "Encapsulation", "Polymorphism"}},
}
