#!/usr/bin/env python3
"""Write the Homebrew formula and the Scoop manifest for a release.

  python3 tools/packages.py v1.1.0 dist/SHA256SUMS     # from the academy/ directory

Reads the archive checksums that tools/release.sh wrote and writes, at the
repository root:

  Formula/academy.rb     so this repository works as a Homebrew tap:
                           brew tap pronexuscodex/academy https://github.com/pronexuscodex/learning_space
                           brew install academy
  bucket/academy.json    so it works as a Scoop bucket:
                           scoop bucket add academy https://github.com/pronexuscodex/learning_space
                           scoop install academy

The release workflow runs this after every release and commits the result,
so the files always point at the newest archives. Python 3 only.
"""
import json, os, re, sys

REPO = "pronexuscodex/learning_space"
HOMEPAGE = f"https://github.com/{REPO}"
DESC = "Offline study companion: from how computers work and C to systems and AI"
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def read_sums(path):
    sums = {}
    for line in open(path):
        m = re.match(r"^([0-9a-f]{64})\s+\*?(\S+)$", line.strip())
        if m:
            sums[m.group(2)] = m.group(1)
    return sums


def archive(version, os_name, arch):
    ext = "zip" if os_name == "windows" else "tar.gz"
    return f"academy-{version}-{os_name}-{arch}.{ext}"


def url(version, name):
    return f"{HOMEPAGE}/releases/download/{version}/{name}"


def formula(version, sums):
    def block(os_name, arch):
        name = archive(version, os_name, arch)
        return f'      url "{url(version, name)}"\n      sha256 "{sums[name]}"'

    return f'''# Generated by academy/tools/packages.py for {version}; do not edit by hand.
class Academy < Formula
  desc "{DESC}"
  homepage "{HOMEPAGE}"
  version "{version.lstrip("v")}"
  license "MIT"

  on_macos do
    on_arm do
{block("darwin", "arm64")}
    end
    on_intel do
{block("darwin", "amd64")}
    end
  end

  on_linux do
    on_arm do
{block("linux", "arm64")}
    end
    on_intel do
{block("linux", "amd64")}
    end
  end

  def install
    bin.install "academy"
  end

  def caveats
    <<~EOS
      Your progress is kept in #{{Dir.home}}/#{{OS.mac? ? "Library/Application Support" : ".local/share"}}/academy,
      so upgrades never touch it. Set ACADEMY_HOME to keep it somewhere else.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/academy -version")
  end
end
'''


def scoop(version, sums):
    def arch(a):
        name = archive(version, "windows", a)
        return {"url": url(version, name), "hash": sums[name], "extract_dir": name.removesuffix(".zip")}

    def auto(a):
        name = archive("v$version", "windows", a)
        return {"url": url("v$version", name), "extract_dir": name.removesuffix(".zip")}

    return {
        "##": f"Generated by academy/tools/packages.py for {version}; do not edit by hand.",
        "version": version.lstrip("v"),
        "description": DESC,
        "homepage": HOMEPAGE,
        "license": "MIT",
        "notes": "Your progress is kept in %LocalAppData%\\academy, so updates never touch it. Set ACADEMY_HOME to keep it somewhere else.",
        "architecture": {"64bit": arch("amd64"), "arm64": arch("arm64")},
        "bin": "academy.exe",
        "checkver": {"github": HOMEPAGE},
        "autoupdate": {
            "architecture": {"64bit": auto("amd64"), "arm64": auto("arm64")},
            "hash": {"url": "$baseurl/SHA256SUMS"},
        },
    }


def as_tuple(v):
    return tuple(int(n) for n in v.lstrip("v").split("."))


def current_version():
    try:
        with open(os.path.join(ROOT, "bucket", "academy.json")) as f:
            return json.load(f)["version"]
    except (OSError, ValueError, KeyError):
        return None


def main():
    if len(sys.argv) != 3 or not re.fullmatch(r"v\d+\.\d+\.\d+", sys.argv[1]):
        sys.exit("usage: tools/packages.py vX.Y.Z path/to/SHA256SUMS")
    version, sums = sys.argv[1], read_sums(sys.argv[2])
    current = current_version()
    if current and as_tuple(current) > as_tuple(version):
        print(f"bucket/academy.json already has {current}, newer than {version}; nothing to do")
        return
    try:
        rb, js = formula(version, sums), scoop(version, sums)
    except KeyError as e:
        sys.exit(f"SHA256SUMS has no line for {e.args[0]}")
    os.makedirs(os.path.join(ROOT, "Formula"), exist_ok=True)
    os.makedirs(os.path.join(ROOT, "bucket"), exist_ok=True)
    with open(os.path.join(ROOT, "Formula", "academy.rb"), "w") as f:
        f.write(rb)
    with open(os.path.join(ROOT, "bucket", "academy.json"), "w") as f:
        json.dump(js, f, indent=4)
        f.write("\n")
    print(f"wrote Formula/academy.rb and bucket/academy.json for {version}")


if __name__ == "__main__":
    main()
