# Generated by academy/tools/packages.py for v1.3.0; do not edit by hand.
class Academy < Formula
  desc "Offline study companion: from how computers work and C to systems and AI"
  homepage "https://github.com/pronexuscodex/learning_space"
  version "1.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/pronexuscodex/learning_space/releases/download/v1.3.0/academy-v1.3.0-darwin-arm64.tar.gz"
      sha256 "b872bea121f4113ee060ad084d0f7f2812c0de398e39835f242a36a60a2ba5e0"
    end
    on_intel do
      url "https://github.com/pronexuscodex/learning_space/releases/download/v1.3.0/academy-v1.3.0-darwin-amd64.tar.gz"
      sha256 "c434f708b05ba03a8cb136b715e0da4abc3d9b9b721e945d8f8a563f5b38b59d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/pronexuscodex/learning_space/releases/download/v1.3.0/academy-v1.3.0-linux-arm64.tar.gz"
      sha256 "b8589a116f548199e3ce4596dbccb149f88ca9a31f4537bc43e3fff9583ba245"
    end
    on_intel do
      url "https://github.com/pronexuscodex/learning_space/releases/download/v1.3.0/academy-v1.3.0-linux-amd64.tar.gz"
      sha256 "fd25a2199d41f14b4f26cf7938f21052bb96556dc8c85465fb61661adaeaab10"
    end
  end

  def install
    bin.install "academy"
  end

  def caveats
    <<~EOS
      Your progress is kept in #{Dir.home}/#{OS.mac? ? "Library/Application Support" : ".local/share"}/academy,
      so upgrades never touch it. Set ACADEMY_HOME to keep it somewhere else.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/academy -version")
  end
end
