# Generated by academy/tools/packages.py for v1.4.0; do not edit by hand.
class Academy < Formula
  desc "Offline study companion: from how computers work and C to systems and AI"
  homepage "https://github.com/pronexuscodex/learning_space"
  version "1.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/pronexuscodex/learning_space/releases/download/v1.4.0/academy-v1.4.0-darwin-arm64.tar.gz"
      sha256 "d8fbb2f4880ee6f119868c0b9248d9517a5a34fe29178deb35a4de3b09b1dcb0"
    end
    on_intel do
      url "https://github.com/pronexuscodex/learning_space/releases/download/v1.4.0/academy-v1.4.0-darwin-amd64.tar.gz"
      sha256 "b536c4ca5050d18678deb22abb354897e6bc00d442d2d805ceb7577bc120cc8c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/pronexuscodex/learning_space/releases/download/v1.4.0/academy-v1.4.0-linux-arm64.tar.gz"
      sha256 "6caae3c623e429d240336a6a6eae010a7ec243b6121e7703a855ba8222d3de50"
    end
    on_intel do
      url "https://github.com/pronexuscodex/learning_space/releases/download/v1.4.0/academy-v1.4.0-linux-amd64.tar.gz"
      sha256 "fb361babef0cbde15ca281696366f58d00ed27efd9bd2c2fefa0ff7da0026249"
    end
  end

  def install
    bin.install "academy"
  end

  def caveats
    <<~EOS
      Your progress is kept in #{Dir.home}/#{OS.mac? ? "Library/Application Support" : ".local/share"}/academy,
      so upgrades never touch it. Set ACADEMY_HOME to keep it somewhere else.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/academy -version")
  end
end
