# Generated by academy/tools/packages.py for v1.2.0; do not edit by hand.
class Academy < Formula
  desc "Offline study companion: from how computers work and C to systems and AI"
  homepage "https://github.com/pronexuscodex/learning_space"
  version "1.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/pronexuscodex/learning_space/releases/download/v1.2.0/academy-v1.2.0-darwin-arm64.tar.gz"
      sha256 "38e6ac18487709894f6ad488960c7124f6814e178fc1d13837affee050ad4615"
    end
    on_intel do
      url "https://github.com/pronexuscodex/learning_space/releases/download/v1.2.0/academy-v1.2.0-darwin-amd64.tar.gz"
      sha256 "232d5652137f12d27e25e59c88bd503f227445f84248e0c70d097ee27c9c6062"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/pronexuscodex/learning_space/releases/download/v1.2.0/academy-v1.2.0-linux-arm64.tar.gz"
      sha256 "f998d6b11baa07305c5169c57f22298093777e07a2136a35a89026b38a61c817"
    end
    on_intel do
      url "https://github.com/pronexuscodex/learning_space/releases/download/v1.2.0/academy-v1.2.0-linux-amd64.tar.gz"
      sha256 "e58cd319abe187a345fd3362769c3cd642f5dc27e0778b54d45179f4e48e37b3"
    end
  end

  def install
    bin.install "academy"
  end

  def caveats
    <<~EOS
      Your progress is kept in #{Dir.home}/#{OS.mac? ? "Library/Application Support" : ".local/share"}/academy,
      so upgrades never touch it. Set ACADEMY_HOME to keep it somewhere else.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/academy -version")
  end
end
